extends Node
## İki dilli metin sistemi. T.t("anahtar", [argümanlar])

var lang := "tr"

func t(key: String, args: Array = []) -> String:
	var d: Dictionary = TR if lang == "tr" else EN
	var txt: String = d.get(key, TR.get(key, key))
	if args.is_empty():
		return txt
	var sargs := []
	for a in args:
		if a is float and a == floor(a):
			sargs.append(str(int(a)))
		else:
			sargs.append(str(a))
	return txt % sargs

const TR := {
	# genel
	"title": "GÖZCÜ", "subtitle": "Scout Kariyeri",
	"new_game": "Yeni Kariyer", "continue": "Devam Et", "language": "Dil: Türkçe",
	"your_name": "Scout adın", "start": "Başla", "back": "‹ Geri", "close": "Kapat", "ok": "Tamam",
	"choose_club": "İş teklifleri", "choose_club_sub": "Kariyerine nerede başlayacaksın?",
	"prestige": "Prestij", "salary_w": "Maaş: %s/hafta", "budget_season": "Seyahat bütçesi: %s/sezon",
	"accept": "Kabul et", 	"season_week": "%s/%s Sezonu • Hafta %s", "preseason": "Hazırlık dönemi",
	"window_open": "Transfer dönemi açık", "manager": "Teknik direktör",
	# sekmeler
	"tab_home": "Ofis",
	# üst çubuk
	"rep": "İtibar", "money": "Cüzdan", "wp": "İş günü", "fatigue": "Yorgunluk", "travel_left": "Seyahat bütçesi",
	# ana ekran
	"home_club": "Kulübün", "home_skills": "Yeteneklerin", "eye": "Göz", "net": "Ağ (bağlantılar)",
	"next_step": "Bu hafta", "end_week": "Haftayı tamamla ›", "end_preseason": "Sezonu başlat",
	"plan_summary_none": "Henüz maç planlamadın. Hafta sekmesinden bir maça git.",
	"plan_summary": "Planın: %s", "standings": "Puan durumu", "courses": "Gelişim",
	"course_eye": "Göz kursu (%s)", "course_net": "Network etkinliği (%s)", "course_rest": "Hafta sonu tatili (%s)",
	"not_enough_money": "Yeterli paran yok.",
	"scout_history": "Kariyer geçmişi",
	# hafta
	"week_matches": "Bu haftanın maçları", "no_matches": "Bu hafta lig maçı yok. Hafta içi video analizi ve kaynaklarla çalış.",
	"sat": "Cumartesi", "sun": "Pazar", "go_match": "Bu maça git", "planned": "✓ Gidiyorsun", "cancel_plan": "Vazgeç",
	"focus_title": "Odak oyuncular (en fazla 3)", "focus_hint": "Tribünde özellikle izleyeceğin oyuncuları seç. Diğerlerini de görürsün ama daha az.",
	"travel_local": "Şehir içi", "travel_bus": "Otobüs (%s km)", "travel_bus_hotel": "Otobüs + otel (%s km)", "travel_plane": "Uçak + otel (%s km)",
	"cost": "Maliyet", "squad": "Kadro", "tbl_hdr": "O   AV   P",
	# görevler
	"tasks_title": "Kulüp talepleri", "no_tasks": "Şu an açık talep yok.",
	"kind_first11": "İlk 11 oyuncusu", "kind_prospect": "Geleceğin yıldızı", "kind_backup": "Tecrübeli rotasyon",
	"task_line": "Pozisyon: %s • Maks. yaş: %s • Bütçe: %s", "task_deadline": "Son tarih: Hafta %s",
	"task_level": "Beklenen seviye: %s ★", "status_open": "Açık", "status_submitted": "Rapor yönetimde",
	"status_done": "Tamamlandı ✓", "status_expired": "Süresi doldu ✗",
	"my_reports": "Raporlarım", "rep_status_pending": "Değerlendiriliyor", "rep_status_signed": "İmzalandı ✓",
	"rep_status_agreed": "Ön anlaşma", "rep_status_rejected": "Reddedildi", "rep_status_filed": "Arşivlendi",
	# oyuncular
	"shortlist": "Takip listem", "search": "Oyuncu ara", "all_leagues": "Tüm ligler", "all_pos": "Tüm mevkiler",
	"age_max": "Yaş ≤ %s", "sort_rating": "Sırala: Form", "sort_age": "Sırala: Yaş", "sort_value": "Sırala: Değer", "sort_known": "Sırala: Bilgim",
	"only_known": "Sadece bildiklerim", "empty_shortlist": "Takip listen boş. Bir oyuncu profilinden ☆ ile ekle.",
	"results": "%s oyuncu",
	# profil
	"age": "Yaş", "nat": "Uyruk", "pos": "Mevki", "foot": "Ayak", "foot_L": "Sol", "foot_R": "Sağ", "club": "Kulüp",
	"value": "Piyasa değeri", "contract": "Sözleşme", "agent": "Menajeri", "injured": "Sakat (%s hafta)",
	"public_stats": "Sezon verisi (herkese açık)", "apps": "Maç", "goals": "Gol", "assists": "Asist", "avg": "Ort. puan",
	"your_view": "Senin değerlendirmen", "ovr_est": "Mevcut seviye", "pa_est": "Potansiyel", "unknown": "Bilinmiyor",
	"known_pct": "Bilgi düzeyi: %%%s", "seen_count": "Canlı izleme: %s • Video: %s",
	"grp_phy": "Fiziksel", "grp_tec": "Teknik", "grp_men": "Zihinsel", "grp_gk": "Kalecilik",
	"hidden": "Gizli özellikler (kaynaklardan)", "hid_unknown": "???",
	"lvl_0": "Düşük", "lvl_1": "Orta", "lvl_2": "Yüksek",
	"src_coach": "antrenörü", "src_agent": "menajeri", "src_journalist": "yerel gazeteci",
	"actions": "Aksiyonlar", "act_video": "Video analizi", "act_coach": "Hocasını ara",
	"act_agent": "Menajerle konuş", "act_journalist": "Gazeteciye sor",
	"act_report": "Rapor yaz", "shortlist_add": "Takibe al", "shortlist_remove": "Takipte",
	"no_wp": "Bu hafta iş günün kalmadı.", "scout_notes": "Maç notların", "history": "Kariyer",
	"hist_line": "%s • %s • %s maç %s gol • ort. %s",
	"src_ok": "%s: %s → %s", "src_nothing": "Bu kaynaktan öğrenebileceğin yeni bir şey yok.",
	"src_fail_coach": "Antrenöre ulaşamadın, telefonlarına dönmedi.", "src_fail_journalist": "Gazeteci işe yarar bir şey bilmiyordu.",
	"src_fail_agent": "Menajer meşguldü.", "video_done": "Video analizi tamamlandı. Teknik özellikler netleşti.",
	# özellikler
	"a_pace": "Hız", "a_stamina": "Dayanıklılık", "a_strength": "Güç", "a_agility": "Çeviklik",
	"a_passing": "Pas", "a_dribbling": "Top sürme", "a_finishing": "Bitiricilik", "a_first_touch": "İlk dokunuş",
	"a_crossing": "Orta", "a_tackling": "Top kapma", "a_heading": "Kafa vuruşu",
	"a_positioning": "Pozisyon alma", "a_vision": "Vizyon", "a_decisions": "Karar verme", "a_composure": "Soğukkanlılık", "a_work_rate": "Çalışkanlık",
	"a_reflexes": "Refleks", "a_handling": "Top tutma",
	"h_professionalism": "Profesyonellik", "h_injury_prone": "Sakatlık eğilimi", "h_big_match": "Büyük maç oyuncusu",
	"h_consistency": "İstikrar", "h_adaptability": "Uyum yeteneği",
	"pos_GK": "Kaleci", "pos_CB": "Stoper", "pos_LB": "Sol bek", "pos_RB": "Sağ bek", "pos_DM": "Ön libero",
	"pos_CM": "Merkez orta saha", "pos_AM": "On numara", "pos_LW": "Sol kanat", "pos_RW": "Sağ kanat", "pos_ST": "Santrfor",
	"grp_GK": "Kaleci", "grp_DEF": "Defans", "grp_MID": "Orta saha", "grp_ATT": "Hücum",
	"style_attack": "Hücum futbolu", "style_defend": "Savunma disiplini", "style_press": "Yoğun pres", "style_possession": "Topa sahip olma", "style_counter": "Kontra atak",
	"pref_young": "gençlere şans verir", "pref_exp": "tecrübe ister", "pref_none": "",
	# rapor
	"report_title": "Scout raporu", "report_for": "Hangi talep için?", "report_cur": "Mevcut seviye tahminin",
	"report_pot": "Potansiyel tahminin", "rec": "Tavsiyen", "rec_sign": "Alınmalı", "rec_monitor": "Takip edilmeli", "rec_reject": "Alınmamalı",
	"submit": "Raporu gönder", "report_sent": "Rapor yönetime gitti. Kararı haftaya öğreneceksin.",
	"report_warn": "Dikkat: Raporun tutmazsa itibarın düşer. Bilgin yetersizse önce daha çok izle.",
	"no_open_task": "Açık talep yok, rapor sadece arşive gider.",
	# maç sonucu
	"obs_title": "Tribün raporu", "standouts": "Göze çarpanlar", "nt_header": "%s — puan %s",
	"week_done": "Hafta tamamlandı", "results_title": "Sonuçlar",
	# sezon sonu
	"season_over": "%s Sezonu bitti", "champion": "Şampiyon: %s", "promoted": "Süper Lig'e yükselenler", "relegated": "Küme düşenler",
	"evals": "Transferlerinin karnesi", "eval_line": "Tahminin %s★/%s★ → gerçek %s★/%s★ • %s maç, ort. %s",
	"rep_change": "İtibar: %s → %s", "over_budget": "Seyahat bütçesini aştın, yönetim memnun değil.",
	"offers": "İş teklifleri", "stay": "Kulübümde kalıyorum", "fired_title": "Görevden alındın", "fired_text": "Yönetim seninle yollarını ayırdı. Yeni bir kulüp seçmelisin.",
	"no_evals": "Bu sezon imzalanan oyuncun yok.",
	# haberler
	"n_hired": "%s seni scout olarak işe aldı. Teknik direktör %s ile çalışacaksın.",
	"n_skill_up_eye": "Göz yeteneğin gelişti: %s", "n_skill_up_net": "Bağlantı ağın genişledi: %s",
	"n_rej_gone": "%s artık bu talep için uygun değil.",
	"n_rej_criteria": "Yönetim %s raporunu reddetti: talep kriterlerine uymuyor.",
	"n_rej_budget": "%s için %s istendi. Bütçe yetmedi.",
	"n_rej_manager": "Teknik direktör %s, %s oyununa uymuyor dedi.",
	"n_rej_manager_age": "Teknik direktör %s, %s için 'yaşlı' dedi.",
	"n_rej_board": "Yönetim %s raporuna ikna olmadı. İtibarını artırman lazım.",
	"n_rej_seller": "%s, %s'i satmayı reddetti.",
	"n_rej_player": "%s şehir değiştirmek istemedi.",
	"n_signed": "TRANSFER: %s, %s'den kadromuza katıldı (%s). Senin raporunla!",
	"n_agreed": "ÖN ANLAŞMA: %s (%s) transfer dönemi açılınca gelecek. Bedel: %s",
	"n_joined": "%s resmen %s formasını giydi.",
	"n_assign_expired": "%s talebinin süresi doldu. Yönetim hayal kırıklığında.",
	"n_new_assign": "Yönetimden yeni bir oyuncu talebi geldi.",
	"n_rival_took": "RAKİP KAPTI: %s, takip ettiğin %s'i transfer etti (%s).",
	"n_ai_transfer": "%s, %s'i %s'den aldı (%s).",
	"n_sacked": "%s'de %s görevden alındı. Yeni teknik direktör: %s.",
	"n_young_star": "Gazete: Genç %s (%s) son haftaların yıldızı. Ortalama %s.",
	"n_champion": "%s şampiyon oldu!",
	"n_your_find": "SENİN KEŞFİN: %s büyük gelişim gösterdi. Adın konuşuluyor.",
	"n_fired": "%s seni görevden aldı.",
	# maç notları
	"nt_dnp": "Bu maçta forma giymedi.", "nt_goals": "%s gol attı.", "nt_assists": "%s asist yaptı.",
	"nt_injured": "%s. dakikada sakatlanarak oyundan çıktı.",
	"nt_bigmatch_hi": "Büyük maçta topu istedi, sorumluluktan kaçmadı.", "nt_bigmatch_lo": "Büyük rakip karşısında sindi, saklandı.",
	"nt_pro_hi": "Maçtan önce ilk ısınmaya çıkan oydu, maç sonu ekstra çalıştı.", "nt_pro_lo": "Isınmaya geç çıktı, kenarda telefonuyla oynuyordu.",
	"nt_pace_hi": "Açık alanda rakiplerinden açık ara hızlı.", "nt_pace_mid": "Hızı yeterli ama fark yaratmıyor.", "nt_pace_lo": "Geri koşularda yavaş kaldı, arkası boşaldı.",
	"nt_stamina_hi": "90 dakika aynı tempoda koştu.", "nt_stamina_mid": "Son 20 dakikada biraz düştü.", "nt_stamina_lo": "60. dakikadan sonra yürümeye başladı.",
	"nt_strength_hi": "İkili mücadelelerde rakiplerini savurdu.", "nt_strength_mid": "Fiziksel mücadelede idare eder.", "nt_strength_lo": "Omuz omuza mücadelelerde kolayca düşüyor.",
	"nt_agility_hi": "Ani yön değiştirmelerde çok çevik.", "nt_agility_mid": "Çevikliği ortalama.", "nt_agility_lo": "Dönüşleri hantal.",
	"nt_passing_hi": "Pas kalitesi ligin üstünde, araya harika toplar attı.", "nt_passing_mid": "Basit pasları doğru yapıyor.", "nt_passing_lo": "Uzun paslarda sürekli top kaybetti.",
	"nt_dribbling_hi": "Dar alanda top sürerken üç kişiyi birden geçti.", "nt_dribbling_mid": "Topla ilerlemeyi biliyor.", "nt_dribbling_lo": "Topla buluştuğunda hemen kaptırıyor.",
	"nt_finishing_hi": "Kaleyi gördüğü an soğukkanlı bitirdi.", "nt_finishing_mid": "Vuruşları isabetli ama sert değil.", "nt_finishing_lo": "Net pozisyonları harcadı.",
	"nt_first_touch_hi": "İlk kontrolü kusursuz, top ayağına yapışıyor.", "nt_first_touch_mid": "Top kontrolü fena değil.", "nt_first_touch_lo": "İlk dokunuşu çok uzak, topu açıyor.",
	"nt_crossing_hi": "Ortaları adrese teslim.", "nt_crossing_mid": "Ortaları idare eder.", "nt_crossing_lo": "Ortaları ya kaleciye ya taca gitti.",
	"nt_tackling_hi": "Zamanlaması harika, temiz top kapıyor.", "nt_tackling_mid": "Top kapmada düzgün.", "nt_tackling_lo": "Müdahalelerde geç kalıp faul yaptı.",
	"nt_heading_hi": "Havada hakim, kafa toplarının çoğunu aldı.", "nt_heading_mid": "Hava toplarında vasat.", "nt_heading_lo": "Hava toplarında zayıf.",
	"nt_positioning_hi": "Hep doğru yerde, oyunu okuyor.", "nt_positioning_mid": "Pozisyon bilgisi yeterli.", "nt_positioning_lo": "Sık sık pozisyon dışı yakalandı.",
	"nt_vision_hi": "Kimsenin görmediği pasları görüyor.", "nt_vision_mid": "Oyunu kurmada standart.", "nt_vision_lo": "Kafasını kaldırmadan oynuyor.",
	"nt_decisions_hi": "Ne zaman pas, ne zaman şut, çok iyi seçiyor.", "nt_decisions_mid": "Kararları çoğunlukla doğru.", "nt_decisions_lo": "Yanlış kararlarla atakları bitirdi.",
	"nt_composure_hi": "Baskı altında bile buz gibi.", "nt_composure_mid": "Baskıda biraz aceleci.", "nt_composure_lo": "Baskı gelince paniğe kapılıyor.",
	"nt_work_rate_hi": "Durmadan pres yaptı, takımı için koştu.", "nt_work_rate_mid": "Çalışkanlığı yeterli.", "nt_work_rate_lo": "Top kaybından sonra geri dönmedi.",
	"nt_reflexes_hi": "İnanılmaz refleks kurtarışları yaptı.", "nt_reflexes_mid": "Kurtarması gerekenleri kurtardı.", "nt_reflexes_lo": "Yakın mesafe şutlarda geç tepki verdi.",
	"nt_handling_hi": "Topu hiç sektirmedi, ellerinde güvende.", "nt_handling_mid": "Top tutma güvenli.", "nt_handling_lo": "Basit topları elinden kaçırdı.",
	"act_train": "Antrenmanı izle",
	"act_meet": "Oyuncuyla görüş",
	"act_rest": "Bir gün dinlen",
	"act_costs": "Her aksiyon 1 iş günü. Antrenman ve görüşme seyahat ister (%s). Hoca €60, gazeteci €30.",
	"apps_s": "maç",
	"cam_tv": "Yayın",
	"cam_wide": "Taktik",
	"cam_close": "Yakın",
	"career": "Kariyer",
	"champion_t": "Şampiyon",
	"course_done": "Yeteneğin gelişti!",
	"days_left": "Bu hafta %s boş iş günün var. Her aksiyon bir gün sürer, Çarşamba U19 günüdür.",
	"days_left_s": "%s gün",
	"ev_pass": "Pas",
	"ev_dribble": "Çalım",
	"ev_shot": "Şut",
	"ev_cross": "Orta",
	"ev_header": "Kafa",
	"ev_press": "Pres",
	"ev_sprint": "Sprint",
	"ev_save": "Kurtarış",
	"ev_tackle": "Top kapma",
	"ev_def_dribble": "Top kaptı",
	"ev_def_header": "Hava topu",
	"ev_def_sprint": "Yarışı kazandı",
	"ev_intercept": "Araya girdi",
	"find_players": "Uygun oyuncu ara",
	"form": "Form",
	"go_u19": "İzle",
	"go_weekend": "Hafta sonuna geç",
	"how_title": "Nasıl oynanır",
	"how_1": "Kulübün sana oyuncu talepleri verir. Doğru oyuncuyu bul, rapor yaz.",
	"how_2": "Maçları 3D stadyumda canlı izle. Odak oyuncuların her pası, çalımı, şutu bilgine dönüşür.",
	"how_3": "Hafta içi: video, antrenman, kaynaklar. Çarşamba: U19 maçları. Altyapı yetenekleri ancak keşfedersen görünür.",
	"how_4": "Raporun tutarsa itibarın artar, büyük kulüpler seni ister. Tutmazsa kovulabilirsin.",
	"newgame_intro": "Türkiye'de bir kulübün scoutu olarak işe başlıyorsun. Gözün ne kadar iyiyse kariyerin o kadar parlar.",
	"knowledge": "Bilgi",
	"latest": "Son gelişmeler",
	"map_home": "%s (sen)",
	"map_match": "Maç",
	"map_planned": "Planlanan",
	"max_age_c": "≤ %s yaş",
	"met_yes": "Görüştün",
	"new_disc": "%s yeni yetenek keşfettin",
	"no_reports": "Henüz rapor yazmadın.",
	"no_tags": "Henüz belirgin güçlü/zayıf yön bilmiyorsun. Daha çok izle.",
	"plan_match": "Planla",
	"pm_shortlist": "Takip",
	"pm_search": "Ara",
	"pm_youth": "Altyapı",
	"preseason_hint": "Hazırlık haftası. Kulüp taleplerine göz at, sonra sezonu başlat.",
	"pts": "puan",
	"report_tags": "Rapordaki öne çıkanlar",
	"report_tags_hint": "İzlediğin özelliklerden seç. Somut gerekçe yönetimi daha çok ikna eder.",
	"res_W": "G",
	"res_D": "B",
	"res_L": "M",
	"rest_done": "Dinlendin, yorgunluğun azaldı.",
	"rival_chip": "%s izliyor",
	"rival_seen": "%s scoutu da tribündeydi! Odakladığın oyunculara ilgi var.",
	"src_training": "antrenman",
	"src_meet": "yüz yüze görüşme",
	"st_watched": "İzlenen maç",
	"st_disc": "Keşif",
	"st_signed": "Transfer",
	"st_tips": "İhbar (sezon)",
	"st_reports": "Raporlarım",
	"st_finds": "Büyük keşif",
	"tasks_open": "%s açık kulüp talebi var",
	"u19_done": "U19 raporu",
	"u19_title": "Çarşamba U19 maçları",
	"u19_hint": "Altyapı oyuncuları veritabanında görünmez. Tek yol tribüne gidip izlemek ya da ihbar almak.",
	"u19_squad": "U19 kadrosu (%s/%s keşfedildi)",
	"u19_unknown": "Bu kulübün altyapısından kimseyi tanımıyorsun.",
	"wed_used": "Bu hafta Çarşamba dolu.",
	"week_n": "Hafta %s",
	"weekend_matches": "Hafta sonu maçları",
	"weeks_left": "%s hafta kaldı",
	"window_short": "Transfer dönemi",
	"yo": "yaş",
	"your_estimate": "Senin tahminin: %s",
	"youth_empty": "Henüz altyapı oyuncusu keşfetmedin. Çarşamba U19 maçlarına git.",
	"youth_hint": "Keşfettiğin altyapı yetenekleri. 19 yaşında A takıma çıkar ya da kaybolurlar.",
	"youth_promoted": "Takip ettiğin gençler A takıma çıktı",
	"title_0": "Bölge scoutu",
	"title_1": "Kıdemli scout",
	"title_2": "Baş scout",
	"title_3": "Scouting direktörü",
	"title_4": "Efsane gözcü",
	"r_pac": "HIZ",
	"r_tec": "TEK",
	"r_pas": "PAS",
	"r_sho": "ŞUT",
	"r_def": "DEF",
	"r_phy": "FİZ",
	"r_ref": "REF",
	"r_han": "TUT",
	"r_pos": "POZ",
	"r_dis": "OYN",
	"r_men": "ZİH",
	"line_out": "Pas %s/%s • Çalım %s/%s • Top kazanma %s/%s • Şut %s/%s",
	"line_gk": "Kurtarış %s/%s • Pas %s/%s",
	"no_footage": "Altyapı maçlarının görüntüsü yok. Canlı izlemelisin.",
	"train_done": "Antrenmanı izledin. Fiziksel ve zihinsel özellikler netleşti.",
	"meet_done": "Oyuncuyla tanıştın. Karakteri hakkında güvenilir bilgi aldın.",
	"already_met": "Bu oyuncuyla zaten görüştün.",
	"nt_rival": "%s scoutu da onu izliyordu.",
	"nt_quiet": "Topla pek buluşmadı, değerlendirmek zor.",
	"d0": "PZT",
	"d1": "SAL",
	"d2": "ÇAR",
	"d3": "PER",
	"d4": "CUM",
	"d5": "CMT",
	"d6": "PAZ",
	"kind_wonderkid": "Altyapı cevheri",
	"mv_assist": "asist: %s",
	"mv_drib": "Çalım",
	"mv_foul": "Faul",
	"mv_fulltime": "MAÇ SONU",
	"mv_goal": "GOL",
	"mv_half": "Devre arası",
	"mv_header": "Kafa vuruşu",
	"mv_hint": "Oyunculara dokunarak odak seç (en fazla 3). Odaktaki oyuncunun her hareketi notlarına geçer.",
	"mv_no_focus": "Henüz odak yok. Sahada bir oyuncuya dokun ya da Oyuncular'dan seç.",
	"mv_pass": "Pas",
	"mv_pick": "Odak oyuncular (%s/3)",
	"mv_players": "Oyuncular",
	"mv_save_held": "Kurtarış",
	"mv_save_parry": "Kurtarış, korner",
	"mv_shot": "Şut",
	"mv_shot_ev": "İsabetli şut",
	"mv_shot_wide": "Dışarı",
	"mv_skip": "Sona atla",
	"mv_tkl": "Top kaz.",
	"mv_to_report": "Notları gör",
	"n_tip": "İHBAR: %s altyapısında konuşulan bir %s var, %s yaşında: %s. Altyapı listene eklendi.",
	"est_range": "%s–%s",
	"est_unsure": "tahmin belirsiz",
	"mv_replay": "TEKRAR",
	"mv_tap_skip": "Takımlar sahada • atlamak için dokun",
	"crash_title": "Oyun beklenmedik kapandı",
	"crash_text": "Oyun son oturumda beklenmedik şekilde kapandı. Kaydın son kayıt noktasına kadar korundu. Aşağıdaki butonla hata kaydını kopyalayıp geliştiriciye gönderirsen sorunu bulmamız çok kolaylaşır.",
	"crash_copy": "Hata kaydını kopyala",
	"crash_copied": "Kopyalandı, mesaj olarak yapıştırabilirsin.",
	"crash_quality": "Tekrar olursa grafik kalitesini düşürmeyi dene:",
	"quality_high": "Grafik: Yüksek",
	"quality_medium": "Grafik: Orta",
	"quality_low": "Grafik: Düşük",
	"sound_on": "Ses: Açık",
	"sound_off": "Ses: Kapalı",
	"cam_stand": "Tribün",
	"cam_goal": "Kale arkası",
	"cam_player": "Oyuncu",
	"mv_hl": "Özet",
	"mv_ff": "HIZLI",
	"mv_live": "CANLI",
	"mv_corner": "Korner",
	"mv_kickoff": "Başlama vuruşu",
	"mv_second": "İkinci yarı",
	"league_SL": "Süper Lig",
	"league_L1": "1. Lig",
	"league_L2A": "2. Lig Beyaz",
	"league_L2B": "2. Lig Kırmızı",
	"league_L3A": "3. Lig 1. Grup",
	"league_L3B": "3. Lig 2. Grup",
	"league_L3C": "3. Lig 3. Grup",
	"league_BAL1": "BAL 1. Grup",
	"league_BAL2": "BAL 2. Grup",
	"league_BAL3": "BAL 3. Grup",
	"league_BAL4": "BAL 4. Grup",
	"tier_1": "Süper Lig",
	"tier_2": "1. Lig",
	"tier_3": "2. Lig",
	"tier_4": "3. Lig",
	"tier_5": "BAL",
	"n_champion_lg": "%s, %s şampiyonu oldu!",
	"approved": "ONAYLANDI",
	"attrs_hint": "• işaretli özellikler mevki için kritik. Aralık daraldıkça bilgin artar.",
	"avg_xi": "İlk 11 seviyesi",
	"bench": "YEDEKLER",
	"career_history": "Kariyer geçmişi",
	"club_budget": "Transfer bütçesi",
	"compare_attrs": "Özellik karşılaştırması",
	"compare_hint": "Takip listenden iki oyuncu seç.",
	"compare_need": "Karşılaştırma için takip listende en az iki oyuncu olmalı.",
	"confidential": "GİZLİDİR",
	"ct_info": "Bilgi",
	"ct_squad": "Kadro",
	"ct_youth": "Altyapı",
	"dossier_no": "Dosya no %s",
	"filters": "Filtreler",
	"fired_stamp": "GÖREVDEN ALINDI",
	"focus_count": "Odak: %s/3 oyuncu",
	"form_code": "Form 7B — Gözlem raporu",
	"goals_s": "gol",
	"identity": "Kimlik",
	"joins_window": "Transfer döneminde katılacak • %s",
	"license_no": "Lisans no %s",
	"license_sub": "Türkiye Futbol Gözlemcileri Birliği",
	"license_title": "Scout lisansı",
	"manager_file": "Teknik direktör dosyası",
	"manager_wants": "Hoca şunlara bakar: %s",
	"market_news": "Piyasa kulisi",
	"matches_sorted": "Önce gün, sonra yakınlık sırası. Bilete dokun: planla ve odak seç.",
	"max_age": "Yaş sınırı",
	"max_value": "Bonservis sınırı",
	"memo_from": "Kimden: %s",
	"memo_first11": "İlk 11'e girecek, hazır bir oyuncu lazım. Vakit kaybetmeyelim.",
	"memo_prospect": "Birkaç yıl içinde patlayacak genç bir isim bul. Potansiyel önemli.",
	"memo_backup": "Kadroya derinlik lazım. Tecrübeli ve uygun fiyatlı olsun.",
	"memo_wonderkid": "Altyapılarda gizli kalmış cevheri bul. Kimse fark etmeden!",
	"moves_title": "Yükselen ve düşenler",
	"my_signings": "Benim transferlerim",
	"nation": "Uyruk",
	"next_title": "Sonraki unvan: %s (%s)",
	"nf_all": "Tümü",
	"nf_career": "Kariyer",
	"nf_club": "Kulüpler",
	"nf_tip": "İhbarlar",
	"nf_transfer": "Transfer",
	"nk_tip": "İhbar",
	"nk_good": "Müjde",
	"nk_bad": "Kötü haber",
	"nk_career": "Kariyer",
	"nk_transfer": "Transfer",
	"nk_club": "Kulüp",
	"nk_press": "Basın",
	"nk_misc": "Gündem",
	"no_academy": "Bu kulübün altyapı takımı yok (3. Lig ve BAL kulüplerinde U19 bulunmaz).",
	"no_history": "Henüz kayıt yok.",
	"no_market": "Henüz transfer kulisi yok.",
	"no_matches_tier": "Bu hafta bu kademede maç yok.",
	"no_news": "Bu başlıkta haber yok.",
	"no_notes": "Bu oyuncu için henüz maç notun yok. Maçta odağa al!",
	"no_plan_day": "plan yok",
	"no_signings": "Henüz önerinle imzalanan oyuncu yok.",
	"offer_letter": "Sayın %s, kulübümüzün gözlemci ekibine katılmanızı teklif ediyoruz.",
	"on_desk": "Masadaki dosyalar",
	"paper_motto": "Futbolun gizli sayfası",
	"paper_name": "GÖZCÜ GAZETESİ",
	"pending_transfers": "Bekleyen transferler",
	"pick_match": "Maç seç",
	"planned_stamp": "PLANLANDI",
	"pm_compare": "Kıyasla",
	"preference": "Tercih",
	"preseason_short": "Hazırlık",
	"probable_xi": "MUHTEMEL 11",
	"proto": "prototip",
	"pt_attrs": "Özellikler",
	"pt_career": "Kariyer",
	"pt_file": "Dosya",
	"pt_notes": "Notlar",
	"rank": "Sıralama",
	"rep_chart": "İtibar grafiği",
	"round_n": "%s. hafta / %s",
	"salary": "Maaş",
	"scouting_dept": "Gözlem departmanı",
	"sent_stamp": "GÖNDERİLDİ",
	"shortlist_hint": "Fotoğrafa dokun, dosyayı aç.",
	"sign_here": "imza:",
	"signature": "İmza",
	"signed_stamp": "İMZALANDI",
	"skills_hint": "Göz: tahmin aralıklarını daraltır. Ağ: ihbar ve kaynak başarısını artırır.",
	"st_career": "Kariyer",
	"st_injured": "SAKAT %s HF",
	"st_matches": "Maçlar",
	"st_myclub": "Kulübüm",
	"st_requests": "Talepler",
	"st_summary": "Özet",
	"st_thisweek": "Bu hafta",
	"st_tracking": "TAKİPTE",
	"st_transfers": "Transferler",
	"st_u19": "U19",
	"style": "Oyun anlayışı",
	"title_kicker": "Gözlemci dosyası • No. 1923",
	"travel": "Yolculuk",
	"travel_budget": "Seyahat bütçesi",
	"travel_hint": "Bütçeyi aşarsan sezon sonunda itibar kaybedersin.",
	"u19_preseason": "U19 maçları sezon başlayınca oynanır.",
	"venue": "Stat",
	"week_report": "HAFTA RAPORU",
	"weekend_plan": "Hafta sonu planı",
	"wt_fixtures": "Fikstür",
	"wt_news": "Gazete",
	"wt_table": "Puan durumu",
	"xp_line": "Deneyim %s/%s",
	"zone_down": "Düşme hattı",
	"zone_up": "Yükselme",
	"sat_long": "Cumartesi",
	"sun_long": "Pazar",
	"tab_news": "Dünya",
	"tab_players": "Oyuncular",
	"tab_tasks": "Görevler",
	"tab_week": "Takvim",
	"music_on": "Müzik: Açık",
	"music_off": "Müzik: Kapalı",
	"tab_team": "Ekip",
	"tm_staff": "Ekibim",
	"tm_pool": "Adaylar",
	"tm_reports": "Ekip raporları",
	"dept_title": "Gözlem departmanı",
	"dept_sub": "Kadro: %s / %s kişi",
	"staff_wages": "Haftalık maaşlar",
	"team_langs": "Ekibin dilleri",
	"slots_hint": "İtibarın ve kulübün büyüdükçe daha fazla kişi işe alabilirsin. Maaşlar seyahat bütçesinden düşer.",
	"role_scout": "Bölge scoutu",
	"role_video": "Video analisti",
	"role_data": "Veri analisti",
	"langs_s": "Diller",
	"st_poached": "TEKLİF ALDI",
	"spec": "Uzmanlık",
	"spec_youth": "Genç yetenekler",
	"spec_first": "Hazır oyuncular",
	"character": "Karakter",
	"pers_optimist": "İyimser (yıldızları şişirir)",
	"pers_pessimist": "Temkinli (yıldızları kısar)",
	"pers_balanced": "Dengeli",
	"pers_lazy": "Rahat (az rapor)",
	"pers_hungry": "Hırslı (çok rapor)",
	"pers_unknown": "Henüz bilinmiyor (6 rapordan sonra)",
	"morale": "Moral",
	"staff_reports_n": "Rapor sayısı",
	"assign_region": "Görev bölgesi",
	"rg_tr_top": "Süper Lig + 1. Lig",
	"rg_tr_mid": "2. Lig",
	"rg_tr_low": "3. Lig + BAL",
	"rg_en": "İngiltere",
	"rg_it": "İtalya",
	"rg_br": "Brezilya",
	"lang_warn": "Bu bölgenin dilini bilmiyor: altyapıda kapılar kapanabilir.",
	"role_desc_scout": "Atandığı bölgede her hafta maç izler, sana yıldız tahminli rapor yollar.",
	"role_desc_video": "Takip listendeki oyuncuların maç videolarını her hafta inceler.",
	"role_desc_data": "İstatistiklerden radar dışı, formda oyuncuları yakalar.",
	"give_raise": "Zam yap (+%25)",
	"raise_done": "Zam yapıldı, kalıyor.",
	"fire": "Kov",
	"hire": "İşe al",
	"staff_full": "Kadro dolu. Önce birini çıkar ya da itibarını yükselt.",
	"staff_hired": "İşe alındı!",
	"staff_gone": "Aday artık müsait değil.",
	"no_staff": "Henüz ekibin yok. Adaylar sekmesinden ilk scoutunu işe al.",
	"pool_hint": "Adaylar 4 haftada bir yenilenir. Göz yeteneği tahminlerin isabetini belirler; karakterini zamanla öğrenirsin.",
	"no_staff_reports": "Ekibinden henüz rapor gelmedi. Scoutlarını bir bölgeye ata.",
	"from_staff": "rapor: %s",
	"staff_views": "Ekibinin görüşü",
	"sr_note_1": "Tribünden göze çarptı, takipte kalmalı.",
	"sr_note_2": "Teknik kapasitesi yüksek, fizik sorusu var.",
	"sr_note_3": "Maç zekası iyi, oyunu okuyor.",
	"sr_note_4": "Ham ama tavanı yüksek görünüyor.",
	"sr_note_5": "İstikrarlı, sürpriz yapmaz.",
	"sr_note_data": "İstatistikleri dikkat çekici.",
	"n_staff_hired": "%s ekibine katıldı (%s).",
	"n_staff_fired": "%s ile yollar ayrıldı.",
	"n_staff_left": "%s rakip kulübün teklifini kabul edip ayrıldı.",
	"n_staff_poach": "Rakip bir kulüp %s'a teklif yaptı! İki hafta içinde zam yapmazsan gidiyor.",
	"n_staff_report": "%s raporu: %s (%s) — %s★, potansiyel %s★",
	"n_staff_data": "Veri analisti %s: %s (%s) son maçlarda ortalama %s.",
	"n_lang": "%s öğrendin. Artık bu ülkede rahat iletişim kurabilirsin.",
	"languages": "Diller",
	"lang_hint": "Yabancı ülkede oyuncu/menajerle görüşmek için dil gerekir (ya da ekibinde bilen biri).",
	"lang_course": "%s kursu (%s)",
	"lang_learned": "Yeni dil öğrendin!",
	"lang_TR": "Türkçe",
	"lang_EN": "İngilizce",
	"lang_IT": "İtalyanca",
	"lang_PT": "Portekizce",
	"lang_ES": "İspanyolca",
	"need_lang": "Bu oyuncuyla konuşmak için dil lazım. Dil kursu al ya da o dili bilen birini işe al.",
	"country_TR": "Türkiye",
	"country_EN": "İngiltere",
	"country_IT": "İtalya",
	"country_BR": "Brezilya",
	"league_EN1": "English Top Division",
	"league_IT1": "Serie Prima",
	"league_BR1": "Brasileirão Série A",
	"abroad_hint": "Yurtdışı maç: uçuş pahalı ve bir iş günün yolda geçer.",
	"abroad_cost": "Yurtdışı: bir iş günün yolculuğa gidecek.",
	"need_travel_day": "Yurtdışına gitmek için boş bir iş günü lazım.",
	"travel_plane_int": "Uçak (%s km)",
	"mv_simulating": "Maç simüle ediliyor… %%%s",
	"locked_s": "(izin yok)",
	"tap_continue": "devam için dokun ▸",
	"sc_you": "Sen",
	"sc_you_ask": "Soruyorsun:",
	"sc_nothing": "Bugün pek bir şey göze çarpmadı. Daha fazla izlemek lazım.",
	"sc_place_train": "Antrenman tesisi • %s",
	"sc_place_video": "Video odası",
	"sc_place_meet": "Otel lobisi • %s",
	"sc_place_phone": "Telefon görüşmesi",
	"sc_place_cafe": "Sahil kafesi • %s",
	"sc_place_board": "Başkanlık makamı",
	"sc_train_intro": "%s sahada. %s tesislerinde kenardan izliyorsun. Bugün neye odaklanacaksın?",
	"sc_video_room": "Video analizi",
	"sc_video_intro": "%s'in son maçlarının görüntüleri hazır. Neye bakacaksın?",
	"foc_phy": "Fizik ve kondisyon (hız, güç, dayanıklılık)",
	"foc_men": "Tavır ve oyun zekâsı (karar, konsantrasyon)",
	"foc_tec": "Teknik çalışma (pas, dokunuş, bitiricilik)",
	"foc_men2": "Pozisyon alma ve kararlar",
	"foc_phy2": "Koşular ve ikili mücadeleler",
	"obsl_hi": "%s: gerçekten iyi. Not defterine yazdın (%s).",
	"obsl_mid": "%s: ortalama, ne iyi ne kötü (%s).",
	"obsl_lo": "%s: zayıf halka gibi duruyor (%s).",
	"sc_prof_0": "Antrenmana son gelen, ilk çıkan o. Hocanın yüzü asık.",
	"sc_prof_1": "İşini yapıyor, fazlası yok.",
	"sc_prof_2": "Herkes gittikten sonra bile ekstra çalışmaya kaldı. Profesyonel.",
	"sc_meet_intro": "%s elini sıkıyor: „Hocam hoş geldiniz, buyurun oturalım.” İki soru sorma fırsatın var.",
	"sc_meet_end": "Görüşme bitti. İzlenimlerin dosyaya işlendi.",
	"q_professionalism": "Antrenman dışında kendine nasıl bakıyorsun?",
	"q_adaptability": "Başka bir şehirde ya da ülkede oynamak ister misin?",
	"q_big_match": "Büyük maçlarda, derbilerde nasıl hissedersin?",
	"q_injury_prone": "Son yıllarda sakatlık yaşadın mı?",
	"q_consistency": "Formun neden iniş çıkışlı oluyor sence?",
	"a_professionalism_0": "Valla hocam antrenman yetiyor bence, gerisi keyif.",
	"a_professionalism_1": "Uyku, beslenme... elimden geldiğince dikkat ediyorum.",
	"a_professionalism_2": "Kendi diyetisyenim var, her sabah ekstra çalışıyorum.",
	"a_adaptability_0": "Ailemden uzak kalamam, burada mutluyum.",
	"a_adaptability_1": "Doğru proje olursa düşünürüm.",
	"a_adaptability_2": "Nereye olursa giderim, yeni bir kültür beni heyecanlandırır.",
	"a_big_match_0": "Kalabalık tribün beni biraz geriyor açıkçası.",
	"a_big_match_1": "Her maç aynı benim için.",
	"a_big_match_2": "Büyük maçlar için yaşıyorum, baskı beni ateşliyor!",
	"a_injury_prone_0": "Hiç ciddi sakatlık yaşamadım, demir gibiyim.",
	"a_injury_prone_1": "Ufak tefek şeyler oldu, normal.",
	"a_injury_prone_2": "Geçen sene uzun süre yattım, hâlâ kendimi koruyorum.",
	"a_consistency_0": "Bazen sahada kayboluyorum, bilmiyorum neden.",
	"a_consistency_1": "Herkes gibi iyi kötü günlerim var.",
	"a_consistency_2": "Hocam ben her maç aynıyım, beni bilirler.",
	"sc_role_coach": "Teknik direktör • %s",
	"sc_role_journalist": "Spor muhabiri • %s",
	"sc_role_agent": "%s'in menajeri",
	"sc_intro_coach": "„Alo, buyrun. %s hakkında mı soracaktınız? Kısa olsun, antrenmana çıkıyorum.”",
	"sc_intro_journalist": "Kahveler geldi. Gazeteci gülümsüyor: „%s mi? Soyunma odasında her şey konuşulur…”",
	"sc_intro_agent": "„Benim oyuncum mu? %s mı? Harika çocuktur, sorun bakalım!”",
	"q3_professionalism": "%s antrenmanlarda nasıl, işine sadık mı?",
	"q3_injury_prone": "%s'in sakatlık durumu nedir?",
	"q3_adaptability": "%s başka bir şehre uyum sağlar mı?",
	"q3_big_match": "%s büyük maçlarda nasıl bir oyuncu?",
	"q3_consistency": "%s her maç aynı performansı verir mi?",
	"s_professionalism_0": "Açık konuşayım, %s pek çalışkan değil. Geceleri dışarıda.",
	"s_professionalism_1": "%s işini yapar, olay çıkarmaz.",
	"s_professionalism_2": "%s gibisi az bulunur, tam bir profesyonel.",
	"s_injury_prone_0": "%s demir gibi, hiç sakatlanmaz.",
	"s_injury_prone_1": "%s ara sıra ufak sakatlıklar yaşar.",
	"s_injury_prone_2": "%s'in kasları sık sık yırtılıyor, dikkat.",
	"s_adaptability_0": "%s memleketinden kopamaz, gurbette zorlanır.",
	"s_adaptability_1": "%s doğru ortamda uyum sağlar.",
	"s_adaptability_2": "%s nereye giderse oraya alışır.",
	"s_big_match_0": "Büyük maçlarda %s'in dizleri titrer.",
	"s_big_match_1": "%s büyük maç küçük maç ayırmaz.",
	"s_big_match_2": "Derbi günü %s bambaşka bir oyuncu olur!",
	"s_consistency_0": "%s bir maç harika, bir maç yok.",
	"s_consistency_1": "%s'in iyi kötü günleri olur.",
	"s_consistency_2": "%s saat gibi, her hafta aynı.",
	"sc_agent_warn": "(Menajerler oyuncularını hep över... bunu not ederken temkinli ol.)",
	"sc_fail_coach": "„Kusura bakmayın, oyuncularım hakkında konuşmam.” Telefon kapandı.",
	"sc_fail_journalist": "Gazeteci kahvesini bitirdi ama işe yarar bir şey söylemedi.",
	"sc_fail_agent": "Menajer konuyu sürekli bonservise getirdi.",
	"st_board": "Yönetim",
	"president": "Başkan",
	"pres_patient": "Sabırlı, uzun vadeli düşünür",
	"pres_ambitious": "Hırslı, büyük hayalleri var",
	"pres_stingy": "Hesapçı, her kuruşu sorar",
	"pres_showman": "Şov sever, manşet ister",
	"board_trust": "Güven",
	"mood_hi": "Başkan senden çok memnun.",
	"mood_mid": "Başkan seni izliyor, sonuç bekliyor.",
	"mood_lo": "Başkanın sabrı azalıyor.",
	"board_perms": "İzinler ve bütçe",
	"perm_abroad": "Yurtdışı gözlem izni",
	"perm_slots": "Onaylı ekip kadrosu",
	"perm_favor": "Başkanın desteklediği oyuncu",
	"none": "yok",
	"board_meeting": "Başkanla görüşme",
	"board_hint": "Yurtdışı izni, ekip kadrosu, bütçe ve zam için başkana gitmelisin. Görüşme bir iş günü sürer; üç haftada bir görüşebilirsin. Çok ısrar etmek güveni düşürür.",
	"board_ask": "Görüşme talep et",
	"meet_preseason": "Sezon başlayınca görüşebilirsin.",
	"meet_wait": "Başkan seni yakın zamanda gördü. Biraz beklemen lazım.",
	"pres_hello_hi": "„Gel %s, otur. Kahve? Senin çalışmalarından memnunuz.”",
	"pres_hello_mid": "„Buyur %s. Vaktim kısıtlı, ne lazım?”",
	"pres_hello_lo": "„%s... Açık konuşayım, beklentimizin altındasın. Dinliyorum.”",
	"pt_abroad": "%s'de gözlem yapmak için izin ve bütçe istiyorum",
	"pt_staff": "Ekibime bir kişi daha almak istiyorum",
	"pt_budget": "Seyahat bütçemi artırmalıyız",
	"pt_push": "Bir oyuncuyu bizzat size önermek istiyorum",
	"pt_raise": "Maaşımın gözden geçirilmesini istiyorum",
	"pt_report": "Sadece çalışmalar hakkında bilgi vermeye geldim",
	"ask_abroad": "„%s pazarı çok değerli, orada gözlerimizin olması lazım.”",
	"ask_staff": "„Tek başıma her yeri göremiyorum. Ekibe bir kişi daha lazım.”",
	"ask_budget": "„Doğru oyuncuyu bulmak için daha çok seyahat etmem gerekiyor.”",
	"ask_push": "„%s için kefilim. Yönetimin desteğini istiyorum.”",
	"ask_raise": "„Emeğimin karşılığını almak istiyorum.”",
	"ask_report": "„Takip ettiğimiz isimleri ve planımızı anlatmak istedim.”",
	"pres_abroad_yes": "„Tamam, %s için izin veriyorum. Bütçene %s ekliyorum. Boş dönme!”",
	"pres_abroad_no": "„%s mı? Önce burada kendini kanıtla.”",
	"pres_staff_yes": "„Peki, ekibin artık %s kişi olabilir.”",
	"pres_staff_no": "„Şu an yeni maaş yükü kaldıramayız.”",
	"pres_staff_rep": "„Önce itibarını yükselt, sonra ekip büyütürüz.”",
	"pres_budget_yes": "„Bütçene %s ekledim. Hesabını sorarım ama.”",
	"pres_budget_no": "„Bütçe ne kadarsa o. İdareli kullan.”",
	"pres_raise_yes": "„Haklısın. Maaşına haftalık %s zam yapıyoruz.”",
	"pres_raise_no": "„Zam mı? Önce büyük bir transfer getir!”",
	"pres_push_yes": "„%s'i yönetim olarak destekleyeceğim. Raporunu gönder.”",
	"pres_push_no": "„%s'i tanımıyorum bile. Teknik direktörle konuş.”",
	"pres_report": "„Güzel, böyle bilgilendirilmeyi severim.” (Güven arttı)",
	"pres_bye_ok": "Başkan elini sıkıp seni kapıya kadar geçirdi.",
	"pres_bye_no": "Başkan telefonuna döndü. Görüşme bitti.",
	"need_board_abroad": "Yurtdışında gözlem için başkandan izin almalısın (Ofis › Yönetim).",
	"sc_notebook": "Not defteri",
	"sc_focus_q": "Bugün neye odaklanacaksın?",
	"sc_spark_hint": "Gözünü dört aç! Oyuncunun etrafında altın halka belirdiği an ekrana dokun. Yakaladığın her an, raporuna fazladan bilgi katar.",
	"spark_caught": "YAKALADIN!",
	"spark_missed": "kaçtı…",
	"spark_now": "ŞİMDİ!",
	"sc_spark_note": "%s özel an yakaladım. Bu çocukta bir şey var.",
	"sc_trait2": "Gözümden kaçmadı: %s konusunda net bir fikrim var artık.",
	"sc_ask_q": "%s. sorun ne olsun?",
	"sc_what_ask": "Ne soracaksın?",
	"sc_noted_trait": "Dosyaya işlendi: %s",
	"sc_board_q": "Başkana ne açacaksın?",
	"sc_push_q": "Hangi oyuncuyu önereceksin?",
	"nt_spark": "✦ Kıvılcım: %s özel an yakaladın. %s konusunda artık net bir fikrin var.",
	"mv_offside": "Ofsayt",
	"mv_yellow": "Sarı kart",
	"mv_red": "Kırmızı kart",
	"mv_2y": "ikinci sarı",
	"mv_penalty": "Penaltı",
	"ev_offside": "ofsayt",
	"plan_same_day": "%s günü zaten %s maçına gidiyorsun. Planı bu maçla değiştirmek ister misin?",
	"plan_replace": "Evet, değiştir",
	"plan_keep": "Hayır, kalsın",
	"obs_rating": "Maç puanı",
}

const EN := {
	"title": "GÖZCÜ", "subtitle": "Scout Career",
	"new_game": "New Career", "continue": "Continue", "language": "Language: English",
	"your_name": "Your scout name", "start": "Start", "back": "‹ Back", "close": "Close", "ok": "OK",
	"choose_club": "Job offers", "choose_club_sub": "Where will your career begin?",
	"prestige": "Prestige", "salary_w": "Salary: %s/week", "budget_season": "Travel budget: %s/season",
	"accept": "Accept", 	"season_week": "Season %s/%s • Week %s", "preseason": "Pre-season",
	"window_open": "Transfer window open", "manager": "Head coach",
	"tab_home": "Office",
	"rep": "Reputation", "money": "Wallet", "wp": "Work days", "fatigue": "Fatigue", "travel_left": "Travel budget",
	"home_club": "Your club", "home_skills": "Your skills", "eye": "Eye", "net": "Network",
	"next_step": "This week", "end_week": "End week ›", "end_preseason": "Start season",
	"plan_summary_none": "No match planned yet. Pick one in the Week tab.",
	"plan_summary": "Your plan: %s", "standings": "Standings", "courses": "Development",
	"course_eye": "Eye course (%s)", "course_net": "Networking event (%s)", "course_rest": "Weekend break (%s)",
	"not_enough_money": "Not enough money.",
	"scout_history": "Career history",
	"week_matches": "This week's matches", "no_matches": "No league games this week. Use the week for video analysis and sources.",
	"sat": "Saturday", "sun": "Sunday", "go_match": "Attend this match", "planned": "✓ Attending", "cancel_plan": "Cancel",
	"focus_title": "Focus players (max 3)", "focus_hint": "Pick who you will watch closely. You still notice others, but less.",
	"travel_local": "Local", "travel_bus": "Bus (%s km)", "travel_bus_hotel": "Bus + hotel (%s km)", "travel_plane": "Flight + hotel (%s km)",
	"cost": "Cost", "squad": "Squad", "tbl_hdr": "P   GD   Pts",
	"tasks_title": "Club requests", "no_tasks": "No open requests right now.",
	"kind_first11": "Starting XI player", "kind_prospect": "Future star", "kind_backup": "Experienced squad player",
	"task_line": "Position: %s • Max age: %s • Budget: %s", "task_deadline": "Deadline: Week %s",
	"task_level": "Expected level: %s ★", "status_open": "Open", "status_submitted": "Report with the board",
	"status_done": "Completed ✓", "status_expired": "Expired ✗",
	"my_reports": "My reports", "rep_status_pending": "Under review", "rep_status_signed": "Signed ✓",
	"rep_status_agreed": "Pre-agreement", "rep_status_rejected": "Rejected", "rep_status_filed": "Filed",
	"shortlist": "Shortlist", "search": "Search players", "all_leagues": "All leagues", "all_pos": "All positions",
	"age_max": "Age ≤ %s", "sort_rating": "Sort: Form", "sort_age": "Sort: Age", "sort_value": "Sort: Value", "sort_known": "Sort: Knowledge",
	"only_known": "Only known", "empty_shortlist": "Your shortlist is empty. Add players with ☆ on their profile.",
	"results": "%s players",
	"age": "Age", "nat": "Nationality", "pos": "Position", "foot": "Foot", "foot_L": "Left", "foot_R": "Right", "club": "Club",
	"value": "Market value", "contract": "Contract", "agent": "Agent", "injured": "Injured (%s weeks)",
	"public_stats": "Season data (public)", "apps": "Apps", "goals": "Goals", "assists": "Assists", "avg": "Avg rating",
	"your_view": "Your assessment", "ovr_est": "Current level", "pa_est": "Potential", "unknown": "Unknown",
	"known_pct": "Knowledge: %s%%", "seen_count": "Watched live: %s • Video: %s",
	"grp_phy": "Physical", "grp_tec": "Technical", "grp_men": "Mental", "grp_gk": "Goalkeeping",
	"hidden": "Hidden traits (from sources)", "hid_unknown": "???",
	"lvl_0": "Low", "lvl_1": "Medium", "lvl_2": "High",
	"src_coach": "former coach", "src_agent": "agent", "src_journalist": "local journalist",
	"actions": "Actions", "act_video": "Video analysis", "act_coach": "Call his coach",
	"act_agent": "Talk to agent", "act_journalist": "Ask a journalist",
	"act_report": "Write report", "shortlist_add": "Shortlist", "shortlist_remove": "Shortlisted",
	"no_wp": "No work days left this week.", "scout_notes": "Your match notes", "history": "Career",
	"hist_line": "%s • %s • %s apps %s goals • avg %s",
	"src_ok": "%s: %s → %s", "src_nothing": "Nothing new to learn from this source.",
	"src_fail_coach": "The coach never called back.", "src_fail_journalist": "The journalist knew nothing useful.",
	"src_fail_agent": "The agent was busy.", "video_done": "Video analysis done. Technical attributes are clearer.",
	"a_pace": "Pace", "a_stamina": "Stamina", "a_strength": "Strength", "a_agility": "Agility",
	"a_passing": "Passing", "a_dribbling": "Dribbling", "a_finishing": "Finishing", "a_first_touch": "First touch",
	"a_crossing": "Crossing", "a_tackling": "Tackling", "a_heading": "Heading",
	"a_positioning": "Positioning", "a_vision": "Vision", "a_decisions": "Decisions", "a_composure": "Composure", "a_work_rate": "Work rate",
	"a_reflexes": "Reflexes", "a_handling": "Handling",
	"h_professionalism": "Professionalism", "h_injury_prone": "Injury proneness", "h_big_match": "Big-game player",
	"h_consistency": "Consistency", "h_adaptability": "Adaptability",
	"pos_GK": "Goalkeeper", "pos_CB": "Centre-back", "pos_LB": "Left-back", "pos_RB": "Right-back", "pos_DM": "Defensive mid",
	"pos_CM": "Central mid", "pos_AM": "Attacking mid", "pos_LW": "Left winger", "pos_RW": "Right winger", "pos_ST": "Striker",
	"grp_GK": "Goalkeeper", "grp_DEF": "Defence", "grp_MID": "Midfield", "grp_ATT": "Attack",
	"style_attack": "Attacking football", "style_defend": "Defensive discipline", "style_press": "High press", "style_possession": "Possession", "style_counter": "Counter-attack",
	"pref_young": "trusts youngsters", "pref_exp": "wants experience", "pref_none": "",
	"report_title": "Scout report", "report_for": "For which request?", "report_cur": "Your current level estimate",
	"report_pot": "Your potential estimate", "rec": "Recommendation", "rec_sign": "Sign", "rec_monitor": "Monitor", "rec_reject": "Don't sign",
	"submit": "Submit report", "report_sent": "Report sent to the board. You'll hear back next week.",
	"report_warn": "Careful: if your report is wrong, your reputation drops. Watch more if unsure.",
	"no_open_task": "No open request; the report will just be filed.",
	"obs_title": "Stand report", "standouts": "Standouts", "nt_header": "%s — rating %s",
	"week_done": "Week complete", "results_title": "Results",
	"season_over": "Season %s is over", "champion": "Champions: %s", "promoted": "Promoted to Super League", "relegated": "Relegated",
	"evals": "Your signings' report card", "eval_line": "Your call %s★/%s★ → actual %s★/%s★ • %s apps, avg %s",
	"rep_change": "Reputation: %s → %s", "over_budget": "You overspent the travel budget. The board is unhappy.",
	"offers": "Job offers", "stay": "Stay at my club", "fired_title": "You've been sacked", "fired_text": "The board has let you go. Choose a new club.",
	"no_evals": "No signings of yours this season.",
	"n_hired": "%s hired you as a scout. You'll work with head coach %s.",
	"n_skill_up_eye": "Your scouting eye improved: %s", "n_skill_up_net": "Your network grew: %s",
	"n_rej_gone": "%s is no longer available for this request.",
	"n_rej_criteria": "The board rejected your report on %s: doesn't fit the request.",
	"n_rej_budget": "%s would cost %s. Over budget.",
	"n_rej_manager": "Head coach %s says %s doesn't fit his style.",
	"n_rej_manager_age": "Head coach %s says %s is too old.",
	"n_rej_board": "The board wasn't convinced by your report on %s. Build your reputation.",
	"n_rej_seller": "%s refused to sell %s.",
	"n_rej_player": "%s didn't want to move cities.",
	"n_signed": "TRANSFER: %s joins us from %s (%s). Your report did it!",
	"n_agreed": "PRE-AGREEMENT: %s (%s) will join when the window opens. Fee: %s",
	"n_joined": "%s officially joined %s.",
	"n_assign_expired": "The %s request expired. The board is disappointed.",
	"n_new_assign": "The board sent a new player request.",
	"n_rival_took": "RIVAL SWOOP: %s signed %s from your shortlist (%s).",
	"n_ai_transfer": "%s signed %s from %s (%s).",
	"n_sacked": "%s sacked %s. New head coach: %s.",
	"n_young_star": "Press: Youngster %s (%s) is the star of recent weeks. Average %s.",
	"n_champion": "%s are champions!",
	"n_your_find": "YOUR DISCOVERY: %s has developed massively. People are talking about you.",
	"n_fired": "%s sacked you.",
	"nt_dnp": "Didn't play in this match.", "nt_goals": "Scored %s.", "nt_assists": "Provided %s assist(s).",
	"nt_injured": "Went off injured in the %sth minute.",
	"nt_bigmatch_hi": "Demanded the ball in a big game, took responsibility.", "nt_bigmatch_lo": "Shrank against a big opponent, hid.",
	"nt_pro_hi": "First out for the warm-up, stayed for extra work after.", "nt_pro_lo": "Late to warm up, on his phone on the bench.",
	"nt_pace_hi": "Far quicker than anyone in open space.", "nt_pace_mid": "Pace is adequate, not decisive.", "nt_pace_lo": "Too slow tracking back, left space behind.",
	"nt_stamina_hi": "Ran at the same tempo for 90 minutes.", "nt_stamina_mid": "Faded slightly in the last 20.", "nt_stamina_lo": "Walking after the hour mark.",
	"nt_strength_hi": "Bullied opponents in duels.", "nt_strength_mid": "Holds his own physically.", "nt_strength_lo": "Easily knocked off the ball.",
	"nt_agility_hi": "Very agile on sharp turns.", "nt_agility_mid": "Average agility.", "nt_agility_lo": "Clumsy when turning.",
	"nt_passing_hi": "Passing is above league level, great through balls.", "nt_passing_mid": "Does the simple passes right.", "nt_passing_lo": "Kept losing long passes.",
	"nt_dribbling_hi": "Beat three men in a tight space.", "nt_dribbling_mid": "Can carry the ball forward.", "nt_dribbling_lo": "Loses it as soon as he gets it.",
	"nt_finishing_hi": "Ice-cold finish the moment he saw goal.", "nt_finishing_mid": "Accurate but not powerful shots.", "nt_finishing_lo": "Wasted clear chances.",
	"nt_first_touch_hi": "Perfect first touch, ball sticks to his foot.", "nt_first_touch_mid": "Decent control.", "nt_first_touch_lo": "Heavy first touch, ball runs away.",
	"nt_crossing_hi": "Crosses delivered right to the address.", "nt_crossing_mid": "Crosses are okay.", "nt_crossing_lo": "Crosses went to the keeper or out.",
	"nt_tackling_hi": "Great timing, clean tackles.", "nt_tackling_mid": "Tackles properly.", "nt_tackling_lo": "Late challenges, gave away fouls.",
	"nt_heading_hi": "Dominant in the air.", "nt_heading_mid": "Average in the air.", "nt_heading_lo": "Weak in aerial duels.",
	"nt_positioning_hi": "Always in the right place, reads the game.", "nt_positioning_mid": "Positioning is adequate.", "nt_positioning_lo": "Often caught out of position.",
	"nt_vision_hi": "Sees passes nobody else does.", "nt_vision_mid": "Standard build-up play.", "nt_vision_lo": "Plays with his head down.",
	"nt_decisions_hi": "Chooses perfectly between pass and shot.", "nt_decisions_mid": "Mostly right decisions.", "nt_decisions_lo": "Killed attacks with bad decisions.",
	"nt_composure_hi": "Ice-cold even under pressure.", "nt_composure_mid": "A bit hurried under pressure.", "nt_composure_lo": "Panics under pressure.",
	"nt_work_rate_hi": "Pressed non-stop, ran for the team.", "nt_work_rate_mid": "Work rate is adequate.", "nt_work_rate_lo": "Didn't track back after losing it.",
	"nt_reflexes_hi": "Incredible reflex saves.", "nt_reflexes_mid": "Saved what he should.", "nt_reflexes_lo": "Slow to react to close-range shots.",
	"nt_handling_hi": "Never spilled a ball, safe hands.", "nt_handling_mid": "Safe handling.", "nt_handling_lo": "Dropped simple balls.",
	"act_train": "Watch training",
	"act_meet": "Meet the player",
	"act_rest": "Rest for a day",
	"act_costs": "Each action takes 1 work day. Training and meetings need travel (%s). Coach €60, journalist €30.",
	"apps_s": "apps",
	"cam_tv": "TV",
	"cam_wide": "Tactical",
	"cam_close": "Close",
	"career": "Career",
	"champion_t": "Champions",
	"course_done": "Skill improved!",
	"days_left": "You have %s free work days this week. Each action takes a day; Wednesday is U19 day.",
	"days_left_s": "%s days",
	"ev_pass": "Pass",
	"ev_dribble": "Dribble",
	"ev_shot": "Shot",
	"ev_cross": "Cross",
	"ev_header": "Header",
	"ev_press": "Press",
	"ev_sprint": "Sprint",
	"ev_save": "Save",
	"ev_tackle": "Tackle",
	"ev_def_dribble": "Won it",
	"ev_def_header": "Aerial",
	"ev_def_sprint": "Won race",
	"ev_intercept": "Intercepted",
	"find_players": "Find matching players",
	"form": "Form",
	"go_u19": "Watch",
	"go_weekend": "Go to weekend",
	"how_title": "How to play",
	"how_1": "Your club gives you player requests. Find the right player and write a report.",
	"how_2": "Watch matches live in a 3D stadium. Every pass, dribble and shot of your focus players becomes knowledge.",
	"how_3": "Weekdays: video, training, sources. Wednesday: U19 games. Youth talents only appear once you discover them.",
	"how_4": "Accurate reports build reputation and attract big clubs. Wrong ones can get you sacked.",
	"newgame_intro": "You start as a scout for a club in Turkey. The better your eye, the brighter your career.",
	"knowledge": "Knowledge",
	"latest": "Latest",
	"map_home": "%s (you)",
	"map_match": "Match",
	"map_planned": "Planned",
	"max_age_c": "≤ %s yrs",
	"met_yes": "Met in person",
	"new_disc": "You discovered %s new talents",
	"no_reports": "No reports yet.",
	"no_tags": "No clear strengths or weaknesses known yet. Watch more.",
	"plan_match": "Plan",
	"pm_shortlist": "Shortlist",
	"pm_search": "Search",
	"pm_youth": "Youth",
	"preseason_hint": "Pre-season week. Check the club requests, then start the season.",
	"pts": "pts",
	"report_tags": "Report highlights",
	"report_tags_hint": "Pick from attributes you've seen. Concrete reasons convince the board.",
	"res_W": "W",
	"res_D": "D",
	"res_L": "L",
	"rest_done": "You rested; fatigue dropped.",
	"rival_chip": "%s watching",
	"rival_seen": "A %s scout was in the stand too! Your focus players are attracting interest.",
	"src_training": "training",
	"src_meet": "in-person meeting",
	"st_watched": "Matches watched",
	"st_disc": "Discoveries",
	"st_signed": "Signings",
	"st_tips": "Tips (season)",
	"st_reports": "My reports",
	"st_finds": "Big finds",
	"tasks_open": "%s open club requests",
	"u19_done": "U19 report",
	"u19_title": "Wednesday U19 games",
	"u19_hint": "Youth players aren't in the database. The only way is to watch from the stand or get a tip.",
	"u19_squad": "U19 squad (%s/%s discovered)",
	"u19_unknown": "You don't know anyone from this academy.",
	"wed_used": "Wednesday is already booked this week.",
	"week_n": "Week %s",
	"weekend_matches": "Weekend matches",
	"weeks_left": "%s weeks left",
	"window_short": "Transfer window",
	"yo": "yrs",
	"your_estimate": "Your estimate: %s",
	"youth_empty": "No youth players discovered yet. Go to Wednesday U19 games.",
	"youth_hint": "Academy talents you discovered. At 19 they join the first team or disappear.",
	"youth_promoted": "Youngsters you tracked joined first teams",
	"title_0": "Regional scout",
	"title_1": "Senior scout",
	"title_2": "Chief scout",
	"title_3": "Scouting director",
	"title_4": "Legendary eye",
	"r_pac": "PAC",
	"r_tec": "TEC",
	"r_pas": "PAS",
	"r_sho": "SHO",
	"r_def": "DEF",
	"r_phy": "PHY",
	"r_ref": "REF",
	"r_han": "HAN",
	"r_pos": "POS",
	"r_dis": "DIS",
	"r_men": "MEN",
	"line_out": "Pass %s/%s • Dribble %s/%s • Won ball %s/%s • Shots %s/%s",
	"line_gk": "Saves %s/%s • Pass %s/%s",
	"no_footage": "There's no footage of academy games. Watch live.",
	"train_done": "You watched training. Physical and mental attributes are clearer.",
	"meet_done": "You met the player and got reliable info on his character.",
	"already_met": "You've already met this player.",
	"nt_rival": "A %s scout was watching him too.",
	"nt_quiet": "Barely touched the ball; hard to judge.",
	"d0": "MON",
	"d1": "TUE",
	"d2": "WED",
	"d3": "THU",
	"d4": "FRI",
	"d5": "SAT",
	"d6": "SUN",
	"kind_wonderkid": "Academy gem",
	"mv_assist": "assist: %s",
	"mv_drib": "Drib",
	"mv_foul": "Foul",
	"mv_fulltime": "FULL TIME",
	"mv_goal": "GOAL",
	"mv_half": "Half-time",
	"mv_header": "Header",
	"mv_hint": "Tap players to focus (max 3). Every action of a focused player goes into your notes.",
	"mv_no_focus": "No focus yet. Tap a player on the pitch or pick from Players.",
	"mv_pass": "Pass",
	"mv_pick": "Focus players (%s/3)",
	"mv_players": "Players",
	"mv_save_held": "Save",
	"mv_save_parry": "Save, corner",
	"mv_shot": "Shot",
	"mv_shot_ev": "Shot on target",
	"mv_shot_wide": "Wide",
	"mv_skip": "Skip to end",
	"mv_tkl": "Won",
	"mv_to_report": "See notes",
	"n_tip": "TIP: There's talk of a %s youth %s, aged %s: %s. Added to your youth list.",
	"est_range": "%s–%s",
	"est_unsure": "rough estimate",
	"mv_replay": "REPLAY",
	"mv_tap_skip": "Teams line up • tap to skip",
	"crash_title": "The game closed unexpectedly",
	"crash_text": "The game closed unexpectedly during the last match. Your save is kept from before the match. Copy the error log below and send it to the developer.",
	"crash_copy": "Copy error log",
	"crash_copied": "Copied — paste it in a message.",
	"crash_quality": "If it happens again, try lowering graphics quality:",
	"quality_high": "Graphics: High",
	"quality_medium": "Graphics: Medium",
	"quality_low": "Graphics: Low",
	"sound_on": "Sound: On",
	"sound_off": "Sound: Off",
	"cam_stand": "Stand",
	"cam_goal": "Behind goal",
	"cam_player": "Player",
	"mv_hl": "Highlights",
	"mv_ff": "FAST",
	"mv_live": "LIVE",
	"mv_corner": "Corner",
	"mv_kickoff": "Kick-off",
	"mv_second": "Second half",
	"league_SL": "Super League",
	"league_L1": "First League",
	"league_L2A": "Second League White",
	"league_L2B": "Second League Red",
	"league_L3A": "Third League Gr. 1",
	"league_L3B": "Third League Gr. 2",
	"league_L3C": "Third League Gr. 3",
	"league_BAL1": "Regional Am. Gr. 1",
	"league_BAL2": "Regional Am. Gr. 2",
	"league_BAL3": "Regional Am. Gr. 3",
	"league_BAL4": "Regional Am. Gr. 4",
	"tier_1": "Super League",
	"tier_2": "First League",
	"tier_3": "Second League",
	"tier_4": "Third League",
	"tier_5": "Regional Am.",
	"n_champion_lg": "%s are champions of %s!",
	"approved": "APPROVED",
	"attrs_hint": "• marks key attributes for the position. Narrower ranges mean better knowledge.",
	"avg_xi": "First XI level",
	"bench": "BENCH",
	"career_history": "Career history",
	"club_budget": "Transfer budget",
	"compare_attrs": "Attribute comparison",
	"compare_hint": "Pick two players from your shortlist.",
	"compare_need": "You need at least two players on your shortlist to compare.",
	"confidential": "CONFIDENTIAL",
	"ct_info": "Info",
	"ct_squad": "Squad",
	"ct_youth": "Academy",
	"dossier_no": "File no %s",
	"filters": "Filters",
	"fired_stamp": "DISMISSED",
	"focus_count": "Focus: %s/3 players",
	"form_code": "Form 7B — Scouting report",
	"goals_s": "goals",
	"identity": "Identity",
	"joins_window": "Joins in the transfer window • %s",
	"license_no": "Licence no %s",
	"license_sub": "Association of Football Scouts",
	"license_title": "Scout licence",
	"manager_file": "Manager file",
	"manager_wants": "The boss looks for: %s",
	"market_news": "Market whispers",
	"matches_sorted": "Sorted by day, then distance. Tap a ticket to plan and pick focus.",
	"max_age": "Age limit",
	"max_value": "Fee limit",
	"memo_from": "From: %s",
	"memo_first11": "I need a ready-made starter. No time to waste.",
	"memo_prospect": "Find a youngster who'll break through in a few years. Potential matters.",
	"memo_backup": "We need depth. Experienced and affordable.",
	"memo_wonderkid": "Find the hidden gem in the academies before anyone else does!",
	"moves_title": "Promoted & relegated",
	"my_signings": "My signings",
	"nation": "Nationality",
	"next_title": "Next title: %s (%s)",
	"nf_all": "All",
	"nf_career": "Career",
	"nf_club": "Clubs",
	"nf_tip": "Tips",
	"nf_transfer": "Transfers",
	"nk_tip": "Tip",
	"nk_good": "Good news",
	"nk_bad": "Bad news",
	"nk_career": "Career",
	"nk_transfer": "Transfer",
	"nk_club": "Club",
	"nk_press": "Press",
	"nk_misc": "News",
	"no_academy": "This club has no youth team (Third League and Regional clubs have no U19).",
	"no_history": "No records yet.",
	"no_market": "No transfer whispers yet.",
	"no_matches_tier": "No matches at this level this week.",
	"no_news": "No news under this heading.",
	"no_notes": "No match notes for this player yet. Focus on him in a match!",
	"no_plan_day": "nothing planned",
	"no_signings": "No player has signed on your recommendation yet.",
	"offer_letter": "Dear %s, we would like you to join our scouting staff.",
	"on_desk": "On your desk",
	"paper_motto": "Football's hidden page",
	"paper_name": "THE SCOUT GAZETTE",
	"pending_transfers": "Pending transfers",
	"pick_match": "Pick a match",
	"planned_stamp": "PLANNED",
	"pm_compare": "Compare",
	"preference": "Preference",
	"preseason_short": "Pre-season",
	"probable_xi": "PROBABLE XI",
	"proto": "prototype",
	"pt_attrs": "Attributes",
	"pt_career": "Career",
	"pt_file": "File",
	"pt_notes": "Notes",
	"rank": "Position",
	"rep_chart": "Reputation chart",
	"round_n": "Round %s / %s",
	"salary": "Salary",
	"scouting_dept": "Scouting department",
	"sent_stamp": "SENT",
	"shortlist_hint": "Tap a photo to open the file.",
	"sign_here": "sign:",
	"signature": "Signature",
	"signed_stamp": "SIGNED",
	"skills_hint": "Eye narrows your estimates. Network improves tips and sources.",
	"st_career": "Career",
	"st_injured": "INJURED %s WK",
	"st_matches": "Matches",
	"st_myclub": "My club",
	"st_requests": "Requests",
	"st_summary": "Overview",
	"st_thisweek": "This week",
	"st_tracking": "TRACKED",
	"st_transfers": "Transfers",
	"st_u19": "U19",
	"style": "Style",
	"title_kicker": "Scout file • No. 1923",
	"travel": "Travel",
	"travel_budget": "Travel budget",
	"travel_hint": "Overspending costs reputation at season end.",
	"u19_preseason": "U19 matches start with the season.",
	"venue": "Stadium",
	"week_report": "WEEKLY REPORT",
	"weekend_plan": "Weekend plan",
	"wt_fixtures": "Fixtures",
	"wt_news": "Gazette",
	"wt_table": "Standings",
	"xp_line": "Experience %s/%s",
	"zone_down": "Relegation",
	"zone_up": "Promotion",
	"sat_long": "Saturday",
	"sun_long": "Sunday",
	"tab_news": "World",
	"tab_players": "Players",
	"tab_tasks": "Tasks",
	"tab_week": "Calendar",
	"music_on": "Music: On",
	"music_off": "Music: Off",
	"tab_team": "Team",
	"tm_staff": "My staff",
	"tm_pool": "Candidates",
	"tm_reports": "Staff reports",
	"dept_title": "Scouting department",
	"dept_sub": "Staff: %s / %s",
	"staff_wages": "Weekly wages",
	"team_langs": "Team languages",
	"slots_hint": "Grow your reputation and club to hire more people. Wages come out of the travel budget.",
	"role_scout": "Area scout",
	"role_video": "Video analyst",
	"role_data": "Data analyst",
	"langs_s": "Languages",
	"st_poached": "OFFER",
	"spec": "Specialty",
	"spec_youth": "Young talents",
	"spec_first": "Ready players",
	"character": "Character",
	"pers_optimist": "Optimist (inflates stars)",
	"pers_pessimist": "Cautious (deflates stars)",
	"pers_balanced": "Balanced",
	"pers_lazy": "Laid-back (few reports)",
	"pers_hungry": "Hungry (many reports)",
	"pers_unknown": "Unknown yet (after 6 reports)",
	"morale": "Morale",
	"staff_reports_n": "Reports",
	"assign_region": "Assigned region",
	"rg_tr_top": "Super + First League",
	"rg_tr_mid": "Second League",
	"rg_tr_low": "Third + Regional",
	"rg_en": "England",
	"rg_it": "Italy",
	"rg_br": "Brazil",
	"lang_warn": "Doesn't speak the local language: academies may stay closed.",
	"role_desc_scout": "Watches matches in the assigned region every week and sends star-rated reports.",
	"role_desc_video": "Studies match footage of your shortlist every week.",
	"role_desc_data": "Finds in-form players under the radar from the numbers.",
	"give_raise": "Give a raise (+25%)",
	"raise_done": "Raise given, they stay.",
	"fire": "Fire",
	"hire": "Hire",
	"staff_full": "Staff full. Let someone go or grow your reputation.",
	"staff_hired": "Hired!",
	"staff_gone": "No longer available.",
	"no_staff": "No staff yet. Hire your first scout from Candidates.",
	"pool_hint": "Candidates refresh every 4 weeks. Eye decides accuracy; you learn their character over time.",
	"no_staff_reports": "No staff reports yet. Assign your scouts to a region.",
	"from_staff": "report: %s",
	"staff_views": "Your staff's view",
	"sr_note_1": "Caught the eye from the stands, keep tracking.",
	"sr_note_2": "Technically gifted, physical question marks.",
	"sr_note_3": "Reads the game well.",
	"sr_note_4": "Raw but high ceiling.",
	"sr_note_5": "Consistent, no surprises.",
	"sr_note_data": "Numbers stand out.",
	"n_staff_hired": "%s joined your staff (%s).",
	"n_staff_fired": "Parted ways with %s.",
	"n_staff_left": "%s accepted a rival club's offer and left.",
	"n_staff_poach": "A rival club made an offer to %s! Give a raise within two weeks or they leave.",
	"n_staff_report": "%s report: %s (%s) — %s★, potential %s★",
	"n_staff_data": "Data analyst %s: %s (%s) averaging %s lately.",
	"n_lang": "You learned %s. You can now talk freely in that country.",
	"languages": "Languages",
	"lang_hint": "Meeting players/agents abroad needs the language (or a staff member who speaks it).",
	"lang_course": "%s course (%s)",
	"lang_learned": "New language learned!",
	"lang_TR": "Turkish",
	"lang_EN": "English",
	"lang_IT": "Italian",
	"lang_PT": "Portuguese",
	"lang_ES": "Spanish",
	"need_lang": "You need the language to talk to this player. Take a course or hire someone who speaks it.",
	"country_TR": "Türkiye",
	"country_EN": "England",
	"country_IT": "Italy",
	"country_BR": "Brazil",
	"league_EN1": "English Top Division",
	"league_IT1": "Serie Prima",
	"league_BR1": "Brasileirão Série A",
	"abroad_hint": "Abroad: flights are expensive and one workday goes to travel.",
	"abroad_cost": "Abroad: one workday will go to travel.",
	"need_travel_day": "You need a free workday to travel abroad.",
	"travel_plane_int": "Flight (%s km)",
	"mv_simulating": "Simulating match… %s%%",
	"locked_s": "(no permit)",
	"tap_continue": "tap to continue ▸",
	"sc_you": "You",
	"sc_you_ask": "You ask:",
	"sc_nothing": "Nothing much stood out today. More watching needed.",
	"sc_place_train": "Training ground • %s",
	"sc_place_video": "Video room",
	"sc_place_meet": "Hotel lobby • %s",
	"sc_place_phone": "Phone call",
	"sc_place_cafe": "Seaside café • %s",
	"sc_place_board": "President's office",
	"sc_train_intro": "%s is out on the pitch. You watch from the sidelines in %s. What will you focus on today?",
	"sc_video_room": "Video analysis",
	"sc_video_intro": "Footage of %s's recent matches is ready. What will you look at?",
	"foc_phy": "Physical (pace, strength, stamina)",
	"foc_men": "Attitude and game intelligence",
	"foc_tec": "Technique (passing, touch, finishing)",
	"foc_men2": "Positioning and decisions",
	"foc_phy2": "Runs and duels",
	"obsl_hi": "%s: genuinely good. Noted (%s).",
	"obsl_mid": "%s: average, nothing special (%s).",
	"obsl_lo": "%s: looks like a weak link (%s).",
	"sc_prof_0": "Last to arrive, first to leave. The coach looks annoyed.",
	"sc_prof_1": "Does his job, nothing more.",
	"sc_prof_2": "Stayed for extra work after everyone left. A real pro.",
	"sc_meet_intro": "%s shakes your hand: “Welcome, please sit.” You get to ask two questions.",
	"sc_meet_end": "Meeting over. Your impressions are on file.",
	"q_professionalism": "How do you look after yourself away from training?",
	"q_adaptability": "Would you play in another city or country?",
	"q_big_match": "How do you feel in big games and derbies?",
	"q_injury_prone": "Any injuries in recent years?",
	"q_consistency": "Why do you think your form goes up and down?",
	"a_professionalism_0": "Honestly, training's enough. The rest is for fun.",
	"a_professionalism_1": "Sleep, diet... I try my best.",
	"a_professionalism_2": "I have my own nutritionist and do extra work every morning.",
	"a_adaptability_0": "I can't be far from my family, I'm happy here.",
	"a_adaptability_1": "If the project is right, I'd consider it.",
	"a_adaptability_2": "I'd go anywhere, new cultures excite me.",
	"a_big_match_0": "Big crowds make me a bit nervous, to be honest.",
	"a_big_match_1": "Every game is the same to me.",
	"a_big_match_2": "I live for big games, pressure fires me up!",
	"a_injury_prone_0": "Never had a serious injury, I'm made of iron.",
	"a_injury_prone_1": "Small knocks, nothing unusual.",
	"a_injury_prone_2": "I was out for months last year, still careful.",
	"a_consistency_0": "Sometimes I disappear on the pitch, I don't know why.",
	"a_consistency_1": "Good days and bad days, like everyone.",
	"a_consistency_2": "I'm the same every game, people know me.",
	"sc_role_coach": "Head coach • %s",
	"sc_role_journalist": "Sports reporter • %s",
	"sc_role_agent": "Agent of %s",
	"sc_intro_coach": "“Hello? About %s? Make it quick, I'm off to training.”",
	"sc_intro_journalist": "Coffee arrives. The reporter smiles: “%s? Everything gets talked about in the dressing room…”",
	"sc_intro_agent": "“My player? %s? Great kid, ask away!”",
	"q3_professionalism": "How is %s in training, is he dedicated?",
	"q3_injury_prone": "What's %s's injury record?",
	"q3_adaptability": "Would %s adapt to a new city?",
	"q3_big_match": "What's %s like in big games?",
	"q3_consistency": "Does %s perform the same every week?",
	"s_professionalism_0": "Frankly, %s isn't a hard worker. Out at night.",
	"s_professionalism_1": "%s does his job, no trouble.",
	"s_professionalism_2": "Few like %s, a true professional.",
	"s_injury_prone_0": "%s is made of iron, never injured.",
	"s_injury_prone_1": "%s gets the odd small injury.",
	"s_injury_prone_2": "%s's muscles tear often, be careful.",
	"s_adaptability_0": "%s can't leave his hometown, struggles away.",
	"s_adaptability_1": "%s adapts in the right environment.",
	"s_adaptability_2": "%s settles anywhere.",
	"s_big_match_0": "In big games %s's knees shake.",
	"s_big_match_1": "%s doesn't care if it's big or small.",
	"s_big_match_2": "On derby day %s is a different player!",
	"s_consistency_0": "%s is brilliant one week, invisible the next.",
	"s_consistency_1": "%s has his ups and downs.",
	"s_consistency_2": "%s is like clockwork.",
	"sc_agent_warn": "(Agents always praise their players... be careful with this note.)",
	"sc_fail_coach": "“Sorry, I don't talk about my players.” He hung up.",
	"sc_fail_journalist": "The reporter finished his coffee but said nothing useful.",
	"sc_fail_agent": "The agent kept steering the talk to transfer fees.",
	"st_board": "Board",
	"president": "President",
	"pres_patient": "Patient, thinks long-term",
	"pres_ambitious": "Ambitious, dreams big",
	"pres_stingy": "Penny-pincher, questions every euro",
	"pres_showman": "Showman, wants headlines",
	"board_trust": "Trust",
	"mood_hi": "The president is very happy with you.",
	"mood_mid": "The president is watching, expecting results.",
	"mood_lo": "The president is running out of patience.",
	"board_perms": "Permits and budget",
	"perm_abroad": "Scouting abroad permit",
	"perm_slots": "Approved staff",
	"perm_favor": "Player backed by the president",
	"none": "none",
	"board_meeting": "Meeting the president",
	"board_hint": "Go to the president for permits abroad, staff, budget and pay. A meeting takes a workday; you can meet every three weeks. Pushing too hard lowers trust.",
	"board_ask": "Request a meeting",
	"meet_preseason": "You can meet once the season starts.",
	"meet_wait": "The president saw you recently. You need to wait a bit.",
	"pres_hello_hi": "“Come in %s, sit. Coffee? We're pleased with your work.”",
	"pres_hello_mid": "“Yes %s. I'm short on time, what do you need?”",
	"pres_hello_lo": "“%s... frankly, you're below expectations. I'm listening.”",
	"pt_abroad": "I want a permit and budget to scout in %s",
	"pt_staff": "I want to add one more person to my staff",
	"pt_budget": "We need to increase my travel budget",
	"pt_push": "I want to recommend a player to you personally",
	"pt_raise": "I'd like my salary reviewed",
	"pt_report": "I just came to update you on our work",
	"ask_abroad": "“The %s market is valuable, we need eyes there.”",
	"ask_staff": "“I can't see everything alone. We need one more scout.”",
	"ask_budget": "“To find the right player I need to travel more.”",
	"ask_push": "“I vouch for %s. I want the board's backing.”",
	"ask_raise": "“I'd like my work to be rewarded.”",
	"ask_report": "“I wanted to brief you on our targets and plans.”",
	"pres_abroad_yes": "“Fine, permit granted for %s. I'm adding %s to your budget. Don't come back empty-handed!”",
	"pres_abroad_no": "“%s? Prove yourself here first.”",
	"pres_staff_yes": "“Alright, your staff can now be %s people.”",
	"pres_staff_no": "“We can't take on more wages right now.”",
	"pres_staff_rep": "“Build your reputation first, then we grow the team.”",
	"pres_budget_yes": "“I've added %s to your budget. I'll want an account of it.”",
	"pres_budget_no": "“The budget is what it is. Use it wisely.”",
	"pres_raise_yes": "“Fair enough. A raise of %s per week.”",
	"pres_raise_no": "“A raise? Bring me a big signing first!”",
	"pres_push_yes": "“I'll back %s on the board. Send your report.”",
	"pres_push_no": "“I don't even know %s. Talk to the coach.”",
	"pres_report": "“Good, I like being kept informed.” (Trust up)",
	"pres_bye_ok": "The president shakes your hand and walks you to the door.",
	"pres_bye_no": "The president turns back to his phone. Meeting over.",
	"need_board_abroad": "You need the president's permit to scout abroad (Office › Board).",
	"sc_notebook": "Notebook",
	"sc_focus_q": "What will you focus on today?",
	"sc_spark_hint": "Keep your eyes open! Tap the screen the moment a golden ring appears around the player. Every moment you catch adds extra detail to your report.",
	"spark_caught": "CAUGHT IT!",
	"spark_missed": "missed…",
	"spark_now": "NOW!",
	"sc_spark_note": "Caught %s special moments. This kid has something.",
	"sc_trait2": "Didn't escape me: I now have a clear read on %s.",
	"sc_ask_q": "What's your question #%s?",
	"sc_what_ask": "What will you ask?",
	"sc_noted_trait": "Filed: %s",
	"sc_board_q": "What will you bring up with the president?",
	"sc_push_q": "Which player will you recommend?",
	"nt_spark": "✦ Spark: you caught %s special moments. You now have a clear read on %s.",
	"mv_offside": "Offside",
	"mv_yellow": "Yellow card",
	"mv_red": "Red card",
	"mv_2y": "second yellow",
	"mv_penalty": "Penalty",
	"ev_offside": "offside",
	"plan_same_day": "You're already going to %s on %s. Swap your plan to this match?",
	"plan_replace": "Yes, swap",
	"plan_keep": "No, keep it",
	"obs_rating": "Match rating",
}
