# İsim havuzları: uyruk kodu -> (ilk adlar, soyadlar). Boşlukla ayrılmış; "_" boşluk yerine.
P = {
"ES": ("Pablo Álvaro Sergio Javier Adrián Diego Hugo Marcos Iker Raúl Carlos Daniel Rubén Óscar Iván Jorge Mario Alejandro Gonzalo Unai Aitor Borja Fran Dani Nacho Rodrigo Pedro Mikel Ander Víctor",
       "García Fernández González Rodríguez López Martínez Sánchez Pérez Gómez Martín Jiménez Ruiz Hernández Díaz Moreno Muñoz Álvarez Romero Navarro Torres Domínguez Gil Vázquez Serrano Ramos Blanco Molina Castro Ortega Rubio Garrido Iglesias Medina Herrera Prieto Cortés"),
"DE": ("Lukas Leon Jonas Finn Felix Maximilian Niklas Tim Jan Paul Luca Moritz Florian Julian Tobias Kevin Marco Sebastian Philipp David Fabian Nico Kai Leroy Timo Joshua Mats Benedikt Dominik Robin",
       "Müller Schmidt Schneider Fischer Weber Meyer Wagner Becker Schulz Hoffmann Koch Richter Klein Wolf Schröder Neumann Schwarz Zimmermann Braun Krüger Hofmann Hartmann Lange Schmitt Werner Krause Meier Lehmann Kaiser Fuchs Vogel Keller Frank Berger Winkler"),
"FR": ("Théo Lucas Hugo Maxime Antoine Kylian Yanis Bastien Clément Enzo Florian Rayan Mathis Nathan Louis Baptiste Adrien Jules Quentin Romain Benjamin Alexis Thomas Wesley Moussa Ibrahim Malo Axel Corentin Dylan",
       "Martin Bernard Dubois Moreau Laurent Girard Roux Fontaine Chevalier Mercier Lefèvre Blanchard Petit Durand Leroy Simon Michel Garnier Faure Rousseau Bonnet Lambert Gauthier Perrin Morel Fournier Guerin Barbier Robin Masson Marchand Dupont Colin Vidal"),
"IT": ("Lorenzo Federico Alessandro Matteo Nicolò Davide Gianluca Andrea Marco Giacomo Sandro Riccardo Francesco Leonardo Domenico Mattia Simone Tommaso Gabriele Stefano Filippo Luca Daniele Pietro Samuele Manuel Christian Valerio Michele Fabio",
       "Rossi Russo Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti De_Luca Mancini Costa Giordano Rizzo Lombardi Moretti Barbieri Fontana Santoro Mariani Rinaldi Caruso Ferrara Galli Martini Leone Longo Gentile Martinelli Vitale Serra"),
"PT": ("João Rúben Diogo Tiago Gonçalo Nuno Rafael André Pedro Bernardo Fábio Rodrigo Francisco Miguel Ricardo Bruno Hugo Vasco Afonso Duarte Martim Tomás Rui Sérgio Luís Paulo Henrique Simão Leandro Telmo",
       "Ferreira Gonçalves Marques Pinto Sousa Mendes Correia Lopes Moreira Neves Vieira Tavares Silva Santos Costa Oliveira Rodrigues Martins Fernandes Pereira Carvalho Ribeiro Almeida Cardoso Teixeira Monteiro Fonseca Matos Nunes Rocha Barbosa Antunes Brito Cunha"),
"NL": ("Daan Sem Bram Lars Jesper Thijs Ruben Stijn Wout Joey Calvin Teun Luuk Milan Jurriën Noa Bart Kenneth Quinten Ryan Mats Tijjani Xavi Jordy Kees Sven Niels Jasper Rick Koen",
       "de_Jong Jansen de_Vries van_den_Berg Bakker Visser Smit Meijer Mulder de_Boer Bos Vos Peters Hendriks van_Leeuwen Dekker Brouwer de_Wit Dijkstra Smits de_Graaf van_der_Meer Kok Jacobs de_Haan Vermeulen van_Dijk Schouten van_Beek Willems Hoekstra Koster Prins Huisman"),
"EN": ("Harry Jack Oliver George Charlie James Jacob Thomas Mason Declan Callum Reece Jordan Kyle Jude Cole Marcus Ollie Ben Aaron Luke Josh Connor Tyler Sam Lewis Alfie Archie Kieran Liam",
       "Smith Jones Taylor Brown Williams Wilson Johnson Davies Robinson Wright Thompson Evans Walker White Roberts Green Hall Wood Jackson Clarke Turner Hill Moore Cooper Ward Morris King Baker Harrison Lewis Mills Carter Bennett Shaw Hughes"),
"SCO": ("Callum Ross Kieran Lewis Ryan Scott Craig Euan Fraser Grant Jamie Lyndon Calum Stuart Andrew Gregor Kenny Angus Billy Ewan Duncan Hamish Ally Jordan Connor",
       "McGregor Robertson Campbell Stewart Anderson MacDonald Scott Murray Reid Clark Fraser Ferguson McLean Paterson Henderson McKenzie Hamilton Gray Kerr Mitchell Craig Wallace Cameron Gordon McKay Burns Dunn Christie Forrest McGinn"),
"IE": ("Seán Conor Cian Darragh Ciarán Oisín Eoin Liam Shane Aaron Evan Jamie Callum Dara Cillian Niall Rory Ronan Kevin Robbie Gavin Alan Dylan Matt Jason",
       "Murphy Kelly O'Sullivan Walsh Smith O'Brien Byrne Ryan O'Connor O'Neill O'Reilly Doyle McCarthy Gallagher O'Doherty Kennedy Lynch Murray Quinn Moore McLoughlin O'Carroll Connolly Daly Brennan Collins Duffy Egan Keane Brady"),
"WAL": ("Gareth Aaron Rhys Dafydd Owain Ieuan Gethin Joe Ben Harry Ethan Kieffer Brennan Neco Wes Chris Dylan Tomos Rhodri Iwan Lloyd Morgan Aled Huw Emyr",
       "Jones Williams Davies Evans Thomas Roberts Hughes Lewis Morgan Griffiths Edwards Owen Price Rees Jenkins Lloyd Powell Pritchard Bowen Vaughan Parry Phillips Howells Pugh Prosser"),
"DK": ("Mads Frederik Mikkel Rasmus Jonas Andreas Christian Emil Mathias Kasper Simon Jesper Nicolai Oliver Magnus Lucas Victor Jens Anders Thomas Morten Kristoffer Pierre Joakim Gustav",
       "Jensen Nielsen Hansen Pedersen Andersen Christensen Larsen Sørensen Rasmussen Jørgensen Petersen Madsen Kristensen Olsen Thomsen Christiansen Poulsen Johansen Møller Mortensen Knudsen Mikkelsen Frederiksen Dahl Lindstrøm"),
"SE": ("Emil Viktor Oscar Jesper Linus Anton Isak Hugo Albin Gustav Erik Johan Filip Alexander Sebastian Marcus Joel Robin Dejan Samuel Ludvig Jens Kristoffer Mattias Pontus",
       "Andersson Johansson Karlsson Nilsson Eriksson Larsson Olsson Persson Svensson Gustafsson Pettersson Jonsson Jansson Hansson Bengtsson Jönsson Lindberg Lindqvist Lindgren Berg Axelsson Bergström Lundberg Lind Lundgren Mattsson Berglund Forsberg Sandberg Holm"),
"NO": ("Martin Kristian Sander Jonas Fredrik Magnus Erling Ola Sondre Håkon Eirik Henrik Mathias Tobias Sigurd Aleksander Jørgen Kasper Vegard Even Torbjørn Stian Andreas Morten Oscar",
       "Hansen Johansen Olsen Larsen Andersen Pedersen Nilsen Kristiansen Jensen Karlsen Johnsen Pettersen Eriksen Berg Haugen Hagen Johannessen Andreassen Jacobsen Dahl Jørgensen Halvorsen Henriksen Lund Sørensen Strand Solberg Ødegaard Berge Moen"),
"FI": ("Teemu Joel Lukas Jere Sami Niko Glen Fredrik Robin Leo Daniel Rasmus Onni Eetu Aleksi Juho Matti Joni Tuomas Ville Jesse Oliver Ilmari Santeri Otto",
       "Korhonen Virtanen Mäkinen Nieminen Mäkelä Hämäläinen Laine Heikkinen Koskinen Järvinen Lehtonen Lehtinen Saarinen Salminen Heinonen Niemi Heikkilä Kinnunen Salonen Turunen Salo Laitinen Tuominen Rantanen Karjalainen Pukki Hradecky Väisänen Raitala Lod"),
"IS": ("Gylfi Aron Jóhann Alfreð Birkir Hörður Rúnar Sverrir Hákon Ísak Arnór Albert Jón Andri Willum Kári Ragnar Viðar Mikael Guðmundur Stefán Davíð Óttar Logi Brynjar",
       "Sigurðsson Gunnarsson Guðmundsson Jónsson Bjarnason Finnbogason Magnússon Þórðarson Haraldsson Kristjánsson Ingason Ólafsson Halldórsson Stefánsson Pálsson Einarsson Arnórsson Sigurjónsson Baldursson Hermannsson"),
"PL": ("Jakub Kacper Mateusz Piotr Bartosz Krzysztof Szymon Kamil Przemysław Michał Tomasz Łukasz Paweł Damian Karol Dawid Adrian Sebastian Patryk Marcin Wojciech Filip Hubert Oskar Igor",
       "Nowak Kowalski Wiśniewski Wójcik Kamiński Lewandowski Zieliński Szymański Woźniak Dąbrowski Kozłowski Jankowski Mazur Kwiatkowski Krawczyk Piotrowski Grabowski Nowakowski Pawłowski Michalski Nowicki Adamczyk Dudek Zając Wieczorek Jabłoński Król Majewski Olszewski Jaworski"),
"CZ": ("Tomáš Jakub Jan Lukáš Ondřej Adam Matěj Patrik Vojtěch David Petr Martin Michal Pavel Filip Daniel Antonín Václav Ladislav Vladimír Jiří Marek Dominik Šimon Alex",
       "Novák Svoboda Novotný Dvořák Černý Procházka Kučera Veselý Horák Němec Marek Pokorný Pospíšil Hájek Král Jelínek Růžička Beneš Fiala Sedláček Doležal Zeman Kolář Navrátil Čermák Souček Hložek Krejčí Coufal Holeš"),
"SK": ("Marek Milan Juraj Ondrej Peter Martin Lukáš Matúš Tomáš Róbert Stanislav Dávid Ivan Patrik Denis Adam László Erik Samuel Norbert Vladimír Ľubomír Branislav Dominik Jakub",
       "Hamšík Škriniar Duda Kucka Lobotka Haraslín Mak Hancko Dúbravka Rodák Bero Strelec Gyömbér Suslov Satka Weiss Pekarík Kováč Horváth Varga Tóth Nagy Baláž Molnár Szabó Lukáč Hudák Čech Polák Kollár"),
"HR": ("Ivan Josip Mateo Domagoj Ante Mario Luka Borna Marin Lovro Petar Nikola Duje Marko Bruno Martin Dominik Kristijan Toni Igor Matija Filip Antonio Karlo Roko",
       "Horvat Kovač Babić Marić Jurić Novak Knežević Vuković Perić Pavić Matić Kovačević Božić Tomić Grgić Pavlović Šarić Lovrić Petrović Radić Brozović Vlašić Sučić Majer Gvardiol Livaković Erlić Budimir Pašalić Stanišić"),
"RS": ("Nemanja Dušan Luka Stefan Aleksandar Marko Filip Uroš Nikola Strahinja Lazar Milan Sergej Andrija Veljko Vanja Ivan Miloš Nenad Đorđe Mihailo Srđan Vladimir Predrag Bogdan",
       "Jovanović Petrović Nikolić Marković Đorđević Stojanović Ilić Pavlović Milošević Lukić Babić Kostić Tadić Mitrović Vlahović Milinković Živković Gudelj Pavlović Lazović Racić Veljković Grujić Ristić Stanković Mladenović Savić Simić Radonjić Birmančević"),
"BA": ("Edin Haris Amar Ermin Benjamin Anel Kenan Adnan Sead Armin Elvir Miralem Emir Dženan Ermedin Rade Nikola Ivan Tarik Amir Asmir Eldar Samir Senad Mirza",
       "Hodžić Begić Mehmedović Kovačević Hadžić Delić Salihović Muratović Husić Omerović Zukić Džeko Pjanić Ahmedhodžić Kolašinac Dedić Gojak Hajradinović Demirović Bajić Tahirović Mujakić Krunić Prevljak Šunjić"),
"SI": ("Jan Žan Luka Matic Nejc Benjamin Petar Timi Jaka Domen Adam Miha Tilen Rok Aljaž Andraž Blaž Vid Gašper Nik",
       "Novak Horvat Kovačič Krajnc Zupančič Potočnik Kovač Mlakar Kos Vidmar Golob Turk Kralj Zupan Bizjak Hribar Kozole Šesko Oblak Elšnik Karničnik Bijol Stojanović Mlakar Gorenc"),
"MK": ("Goran Eljif Enis Bojan Darko Aleksandar Stefan Ezgjan Arijan Visar Ivan Jani Kristijan Nikola Tihomir Boban Dimitar Filip Milan Marjan",
       "Pandev Elmas Bardhi Ristovski Velkovski Alioski Nikolov Trajkovski Musliu Churlinov Atanasov Spirovski Ademi Bejtulai Zajkov Dimitrievski Miovski Babunski Kostovski Stojanovski"),
"BG": ("Ivan Georgi Dimitar Petar Nikolay Kiril Stefan Martin Hristo Aleksandar Todor Valentin Atanas Radoslav Plamen Kristian Viktor Ilia Vasil Borislav",
       "Ivanov Georgiev Dimitrov Petrov Nikolov Hristov Stoyanov Todorov Iliev Angelov Atanasov Kostov Marinov Popov Yordanov Kolev Vasilev Despodov Krastev Petkov"),
"RO": ("Andrei Alexandru Ionuț Răzvan Florin Nicolae Dennis Ianis Vlad Mihai Bogdan Cristian Adrian Valentin Darius Radu Ștefan Gabriel Marius Cătălin",
       "Popescu Ionescu Popa Stan Dumitru Stoica Gheorghe Matei Ciobanu Moldovan Rusu Munteanu Constantin Mitrea Hagi Drăgușin Răducioiu Marin Nedelcu Tănase Coman Burcă Man Mihăilă Stanciu"),
"HU": ("Dominik Ádám Bence Dániel Roland Péter Attila Zsolt Milos Kevin Barnabás Botond Márton Gergő Balázs András Tamás László Norbert Krisztián",
       "Nagy Kovács Tóth Szabó Horváth Varga Kiss Molnár Németh Farkas Balogh Papp Takács Juhász Lakatos Mészáros Oláh Simon Rácz Fekete Szoboszlai Sallai Orbán Kerkez Gulácsi"),
"GR": ("Giorgos Dimitris Kostas Nikos Giannis Christos Panagiotis Vasilis Thanasis Michalis Lazaros Anastasios Sotiris Stelios Fotis Pantelis Manolis Tasos Petros Alexandros",
       "Papadopoulos Pappas Oikonomou Georgiou Papageorgiou Vlachos Konstantinidis Nikolaidis Karagiannis Dimitriou Makris Ioannidis Athanasiou Bakasetas Mavropanos Tzolis Masouras Pelkas Mantalos Vlachodimos"),
"AL": ("Arbër Ermir Elseid Kristjan Armando Taulant Berat Myrto Klaus Nedim Ardian Rey Marash Jasir Endrit Arlind Ylber Qazim Medon Mario",
       "Hoxha Shehu Gjoka Krasniqi Berisha Broja Asllani Bajrami Ismajli Laçi Uzuni Manaj Djimsiti Strakosha Çikalleshi Daku Hysaj Ramadani Kumbulla Gjimshiti"),
"XK": ("Vedat Milot Arbër Florent Amir Edon Lumbardh Leart Elbasan Fidan Donat Mirlind Toni Valon Bernard Albion Ilir Besar Fisnik Arijanet",
       "Muriqi Rashica Zeneli Hadergjonaj Rrahmani Berisha Krasniqi Kryeziu Gashi Morina Shala Thaqi Hajdari Vojvoda Aliti Paqarada Muslija Bytyqi Dresevic Halimi"),
"RU": ("Aleksandr Dmitri Sergei Andrei Alexei Ivan Maksim Artyom Nikita Igor Pavel Roman Denis Anton Vladislav Kirill Mikhail Yegor Danila Fyodor",
       "Ivanov Smirnov Kuznetsov Popov Sokolov Lebedev Kozlov Novikov Morozov Petrov Volkov Solovyov Vasiliev Zaitsev Pavlov Semyonov Golubev Vinogradov Bogdanov Vorobyov Fyodorov Mikhailov Belyaev Tarasov Belov"),
"UA": ("Andriy Oleksandr Mykola Viktor Ruslan Taras Bohdan Vitaliy Serhiy Yevhen Mykhailo Artem Oleh Illia Vladyslav Roman Heorhiy Danylo Yaroslav Maksym",
       "Shevchenko Kovalenko Bondarenko Tkachenko Kravchenko Melnyk Boyko Lysenko Moroz Marchenko Rudenko Savchenko Kovalchuk Polishchuk Tymchyk Zinchenko Mudryk Yaremchuk Dovbyk Sudakov"),
"GE": ("Giorgi Levan Otar Luka Saba Zuriko Budu Davit Nika Lasha Khvicha Guram Jaba Anzor Irakli Sandro Valeri Tornike Gabriel Vako",
       "Beridze Kapanadze Gelashvili Lomidze Tsiklauri Mamardashvili Kvaratskhelia Chakvetadze Lochoshvili Mikautadze Kiteishvili Zivzivadze Davitashvili Kashia Kakabadze Shengelia Kvekveskiri Gvilia Lobjanidze Sigua"),
"AM": ("Henrikh Tigran Artur Vahan Eduard Gevorg Karen Aram Norberto Hovhannes Davit Narek Arman Varazdat Sargis Edgar Erik Grant Lucas Khoren",
       "Mkhitaryan Barseghyan Hovhannisyan Spertsyan Haroyan Bichakhchyan Ranos Adamyan Dashyan Grigoryan Harutyunyan Sargsyan Petrosyan Ghazaryan Avetisyan Manucharyan Karapetyan Hakobyan Babayan Simonyan"),
"AZ": ("Mahir Emin Ramil Bahlul Toral Rahil Elvin Ozan Renat Anatoliy Abbas Namiq Tural Rustam Elnur Aydin Ismayil Hojjat Rufat Kamal",
       "Mammadov Aliyev Hasanov Huseynov Guliyev Ismayilov Abbasov Nuriyev Sheydayev Mahmudov Dadashov Garayev Bayramov Mustafazade Akhundov Jafarov Salahli Medvedev Abdullayev Qurbanov"),
"KZ": ("Nursultan Islam Abat Bauyrzhan Askhat Yerkebulan Ramazan Maxim Dastan Askar Temirlan Aybol Galymzhan Marat Sultan Daniyar Azat Olzhas Timur Arman",
       "Zhaksylykov Abiken Seydakhmet Kuat Tagybergen Vorogovsky Shomko Zainutdinov Beysebekov Astanov Islamkhan Suyumbayev Marochkin Darabayev Alip Nurgaliyev Bystrov Sergeyev Kenzhebek Orazov"),
"IL": ("Eran Manor Dor Liel Mohammad Tai Shon Oscar Gavriel Yarden Itay Eli Neta Omri Dean Ido Ofir Yonatan Roy Sun",
       "Zahavi Solomon Peretz Abada Abu_Fani Baribo Weissman Gloukh Kanichowsky Shua Turgeman Dasa Lavi Gandelman Biton Cohen Levi Mizrahi Peretz Avraham"),
"EE": ("Karol Mattias Henri Konstantin Ragnar Joonas Rauno Martin Erik Märten Kristo Rocco Robert Artur Vlasiy Sander Markus Tanel Ken Siim",
       "Mets Käit Anier Vassiljev Klavan Sappinen Sinyavskiy Tamm Saar Sepp Mägi Kask Kukk Rebane Ilves Pärn Koppel Lepik Kuusk Teras"),
"LV": ("Vladislavs Roberts Artūrs Kristers Jānis Dmitrijs Andrejs Raivis Eduards Dāvis Mārcis Kaspars Antonijs Ralfs Gints Rūdolfs Krišjānis Edgars Vitālijs Aleksejs",
       "Gutkovskis Uldriķis Zjuzins Ikaunieks Tobers Savaļnieks Jurkovskis Emsis Ontužāns Krollis Balodis Bērziņš Kalniņš Ozoliņš Liepiņš Kļaviņš Jansons Vītols Zariņš Lācis"),
"LT": ("Fedor Gvidas Justas Arvydas Pijus Artemijus Domantas Vykintas Ovidijus Edgaras Linas Modestas Tomas Paulius Gratas Armandas Matas Rokas Karolis Deividas",
       "Černych Gineitis Lasickas Novikovas Sirvys Tutyškinas Šimkus Slivka Verbickas Utkus Kazlauskas Jankauskas Petrauskas Stankevičius Vasiliauskas Žukauskas Butkus Paulauskas Urbonas Kavaliauskas"),
"MT": ("Teddy Jodi Zach Kurt Paul Matthew Enrico Juan Yannick Alexander Jean Luke Cain Ryan Steve Andrei Karl Myles Basil Shaun",
       "Teuma Jones Muscat Shaw Mbong Grech Pepe Borg Camilleri Vella Farrugia Zammit Galea Micallef Attard Caruana Agius Abela Cassar Mifsud"),
"LU": ("Gerson Danel Leandro Maxime Laurent Christopher Florian Sébastien Vincent Mica Dirk Yvandro Edvin Seid Eldin Olivier Aiman Tim Kevin Lars",
       "Rodrigues Sinani Barreiro Chanot Jans Martins Bohnert Thill Moreira Carlson Pinto Borges Muratovic Jahier Dardari Mahmutovic Olesen Schon Deville Kerger"),
"FO": ("Hallur Gunnar Jóannes Sølvi Brandur Klæmint Rógvi Heini Teitur Viljormur Hanus Gilli Árni Pætur René Odmar Meinhard Andrias Ári Jákup",
       "Hansson Vatnhamar Bjartalíð Olsen Davidsen Hendriksson Joensen Nielsen Jacobsen Lamhauge Petersen Edmundsson Frederiksberg Johansen Sørensen Mortensen Thomsen Danielsen Poulsen Højgaard"),
"CA": ("Marc Jordi Pau Àlex Joan Xavier Ricard Gerard Sergi Albert Oriol Aleix Arnau Nil Martí Biel Iker Eric Txus Ludovic",
       "Pujol Vila Soler Puig Ferrer Casals Riera Rovira Martí Sala Torres Garcia Llorente Rebés San_Nicolás Vieira Alavedra Pons Font Serra"),
"BR": None, "AR": None, "UY": None, "NG": None, "SN": None, "GH": None, "CM": None, "MA": None, "GE_": None,
}
# Ülke -> uyruk havuzları (oyuncu uyruğu ülke kodu; isimler buradan)
POOL_OF = {
 "BE": ["NL", "FR"], "CH": ["DE", "FR", "IT"], "AT": ["DE"], "LU": ["LU", "FR", "PT"], "ME": ["RS"], "BY": ["RU"],
 "MD": ["RO"], "CY": ["GR"], "AD": ["CA", "ES"], "SM": ["IT"], "GI": ["EN", "ES"], "NIR": ["EN", "IE"],
}
